### ISSUE TITLE
select keybindings

### ISSUE THREAD

**Issue by rornor** [nteract/archived-desktop-app#1033]
Guys, great work!

Was wondering if I can set keybinding as in jupyter, where I set code mirror to sublime-text bindings?

TIA

**Comment by rgbkrk** [comment]
We don't have configuration available for that yet. However, our path for it is pretty clean. I made emacs bindings work in https://github.com/nteract/nteract/issues/963.

Closing, since this is a duplicate of #963. Feel free to re-open if you want to. We'll keep on this and make sure you have a nice way of setting your keybindings.

**Comment by rornor** [comment]
Ok, thanks :)
