### ISSUE TITLE
Notebook printing support

### ISSUE THREAD

**Issue by beojan** [nteract/archived-desktop-app#1059]
Is printing support (using nbconvert) a possibility?

**Comment by captainsafia** [comment]
Hello @beojan! Thanks for opening this issue!

Printing support is indeed possible. Since we are using Electron (a boiled-down version of the Chrome browser), we have access to the same printing functionality that is available in your browser.

If you're interested in helping build this, let me know and I can guide you through a contribution.

**Comment by beojan** [comment]
I am interested in helping build this, though my experience with JavaScript (esp. Node.js) is almost non-existent.

**Comment by rgbkrk** [comment]
Luckily there is next to zero JS to write for this - it's primarily writing a print stylesheet that incorporates the theme (CSS variables): https://www.smashingmagazine.com/2011/11/how-to-set-up-a-print-style-sheet/

On the JS side, it's a matter of adding in the menu option.

**Comment by beojan** [comment]
> Luckily there is next to zero JS to write for this - it's primarily a case of writing a print stylesheet that incorporates the theme (CSS variables)

Is there anything preventing just using the Jupyter notebook print stylesheet for this?

**Comment by lgeiger** [comment]
@beojan I guess we have to try it out 😉 

You can take a look at the [Electron API demo app](http://electron.atom.io/#get-started). They have a example and a style sheet there.

**Comment by rgbkrk** [comment]
Done in #1358 (as well as some follow on PRs)!
