### ISSUE TITLE
Ask user to save before global unload function

### ISSUE THREAD

**Issue by LBKinson** [nteract/archived-desktop-app#1090]
Use `beforeunload` to ask user about saving before closing.

**Comment by captainsafia** [comment]
We'll need to use the `dialog` option in electron in order to facilitate this popup. There are a couple examples of us using Electron's `dialog` menu in our code to impact user action. [Here](https://github.com/nteract/nteract/blob/93128ac28dc8da0d9ccd14d0b80f81b3e7322c76/src/main/cli.js#L71) is an example.

Marking this as new-contributor-friendly with mentorship from me available via [Slack](http://slack.nteract.in/).

**Comment by rgbkrk** [comment]
Taking away the `new-contributor-friendly` tag on this one because it involves a lot more coordination with the main thread.
