### ISSUE TITLE
Initial cells wrong size

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1223]
Initial empty notebook looks like this (notice the extra height):

![screen shot 2016-11-20 at 1 48 17 pm](https://cloud.githubusercontent.com/assets/836375/20466405/0a260754-af28-11e6-89cc-f38b222b0038.png)

When creating new cells, they're all the right height:

![screen shot 2016-11-20 at 1 49 54 pm](https://cloud.githubusercontent.com/assets/836375/20466412/3c760704-af28-11e6-8799-2caf9f19b337.png)

Whereas if you resize the window it resets back to the right size:

![screen shot 2016-11-20 at 1 49 09 pm](https://cloud.githubusercontent.com/assets/836375/20466409/224d8df2-af28-11e6-8f80-2c2ca3c4e540.png)

If you have a bigger empty notebook on load they're all the wrong size:

![screen shot 2016-11-20 at 1 50 43 pm](https://cloud.githubusercontent.com/assets/836375/20466416/59280c1c-af28-11e6-93f8-612bbee994c3.png)

I have a few hunches, I'll just post this issue for now and hope someone can tackle it.

**Comment by thomasballinger** [comment]
There's a `margin-bottom: -11px;` style that isn't being applied to these extra-tall cells in the `class="CodeMirror-sizer"` div.

This seemed to be caused by https://github.com/codemirror/CodeMirror/blob/5fc55e8227b3c0d1d8e3178a45fbb37f6f581e48/src/display/update_display.js#L46 not clipping enough because there doesn't seem to be a scrollbar present; a scrollbar should cause a difference between `display.scroller.offsetWidth` and `display.scroller.clientWidth`, but when this runs the first time these values are the same.

So maybe some kind of timing issue with scrollbars? Edit: it's definitely some kind of race condition; wrapping the resizing code in maybeClipScrollbars in a `setTimeout(function(){...}, 0)` fixes the problem.

Next step is probably to create a minimal repro for codemirror or to figure out if we're doing something we aren't supposed to.
