### ISSUE TITLE
Tooltip for function signature/docstring

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1254]
In the jupyter notebook `Shift-Tab` will bring up a tooltip showing the function signature/docsting whcih is incredibly handy.  It would be great if this were also available in nteract.

**Comment by rgbkrk** [comment]
Note: this is the introspection API, which we have available for business logic. Most of the work that needs to be done is UI -- if anyone wants help, let me know.

**Comment by alexandercbooth** [comment]
I find this feature super useful, too. @rgbkrk I'd be happy to work on this if you wouldn't mind helping me get started.

**Comment by rgbkrk** [comment]
Great!

## Precursors

Read up on [how we do code completion](https://github.com/nteract/nteract/blob/7281db7ce5b3f2fbe06d91b4ac88c34b20c7430f/src/notebook/components/cell/codemirror/complete.js). The messaging pattern is pretty similar, except you'll be sending an `inspect_request` and receiving an `inspect_reply`. The [introspection docs in jupyter-client](http://jupyter-client.readthedocs.io/en/latest/messaging.html#introspection) are really specific about what is provided.

In CodeMirror you're going to want to play with [`cm.addWidget`](https://codemirror.net/doc/manual.html#addWidget) which lets you add a DOM node at a position in the editor. You'll have to clean up that DOM node somehow, I'm not sure what the best user experience will be there yet. ❗️ ❕ 

## Likely steps to iterate with

* Register a key binding to invoke a function for introspection (you can just make this `console.log` stuff)
* Create the observable similar to our completion logic
* Hook that observable up to the callback created above
* In the subscription to the observable, have it create a silly widget (for now)
* Since the introspection API returns `display_data` style bundles, you'll want to use our transforms which means you'll need to use React (`ReactDOM.render(<Component />, el)`)

Good luck, let me know if you get stuck with any of this. It's quite a bit to figure out and manage.

**Comment by alexandercbooth** [comment]
This is really thorough, thanks Kyle! I'll work on a first draft and submit a WIP (with copious questions 😅) over the next couple of days.

Thanks!!
