### ISSUE TITLE
Continue comment when inserting a newline

### ISSUE THREAD

**Issue by fbrundu** [nteract/archived-desktop-app#1258]
Hi,
I would like to propose a small feature request: when writing a comment it would be useful to make nteract add automatically a comment symbol (e.g. `#` in Python) as soon as the user goes to the next line (inserting a newline). What do you think?

Thanks,
Francesco

**Comment by captainsafia** [comment]
Hello Francesco! Thanks for opening this issue! 🎉 

This is certainly possible using the [comment add-on](http://codemirror.net/doc/manual.html#addons) in CodeMirror and some JavaScript on our end. If you're interested in implementing this, I'd be glad to help you through it. Otherwise we can leave this open and see if anyone else can tackle it!

**Comment by fbrundu** [comment]
Hi Safia,
thanks for the prompt reply.
I would like to implement it but currently I have no time to do it.
I think it's better to leave it open and see if anyone else can implement it.

Thanks,
Francesco

**Comment by rgbkrk** [comment]
We now have the comment addon setup. How's this on master now?

**Comment by rgbkrk** [comment]
On master and in the latest release, automatic commenting is not happening. This is still a fresh feature request.
