### ISSUE TITLE
nteract as a web app

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1346]
This is a bit of a high level overview of what we need to make nteract available as a web application in addition to components and modules for people to build their own (see #301) or for using our transforms in a standard way in JupyterLab (as @gnestor has done by grabbing the code and maintaining separately).

We ended up bringing in `react-jupyter-display-area` as well as `react-transformime` into this repository which helped us iterate faster and create a tighter build. We swore that we would export these again as part of a monorepo and that time is certainly upon us.

Here's how I imagine this repository will become laid out, as a top level:

```
packages/ # lerna style modules
electronApp/ # uses the lerna modules to compose the electron app
webApp/ # uses the lerna modules to compose a web app
```

My assumption is that the web app will build upon the jupyter notebook server. I'm (personally) not trying to support a standalone single user server for nteract, the primary reason I think I have to build a standalone frontend is to make sure that the exported components are useful while working on [a multi user server](https://github.com/nteract/commuter).

## Precursors

In order to ease maintenance burden of these modules, we've been decoupling components and reducers while also stabilizing our base. In progress issues:

* [x] [Refactor components to remove Redux logic](https://github.com/nteract/nteract/issues/1288)
* [x] Finish flow typing reducers
* [x] Refactor Rx usage to use operator patching rather than bulk import ~~`const Rx = require('rxjs/Rx')`~~

## Web app necessities

* [x] Menu components
  * [x] Create mocks in https://github.com/nteract/mocks
  * [x] Develop components with callbacks (that someone can hook up to dispatch events for the notebook)
* [x] Dashboard - in progress in [commuter](https://github.com/nteract/commuter)

## Monorepo

This may need to be done in stages to minimize pain. Suggested pathway:

* Export everything as a mega lerna package
* Extract smaller and smaller pieces that are decoupled
  * [x] commutable
  * [x] transforms
  * [ ] display area

--------------------------------------

I'll continue to update the above with an outline as we push towards this. What else is a necessity here?

**Comment by peggyrayzis** [comment]
After the provider refactor, I think we should spend some time making our components more composable. Right now, we make a lot of assumptions about what a notebook should and should not have. For example, we embed the StatusBar into the Notebook but what if the end user wants to embed their own status bar? What if the user wants to display different buttons in the Cell Creator menu? Today, we don't support either of those use cases. I really like [Victory](https://github.com/FormidableLabs/victory) as an example of a completely composable library - it makes no assumptions on what is included in a chart and leaves the decision completely up to the user.

We should also think about integrating our CSS into JS to allow users to pass in custom styles through a style prop that will override our defaults. I'm most familiar with [Aphrodite](https://github.com/Khan/aphrodite) because it's really similar to React Native StyleSheet, but I'm open to any other libraries here. Here's an example of what it would look like:

```
// our default
const ColoredDiv = ({}) => <div style={styles.coloredDiv} />
const styles = StyleSheet.create({ coloredDiv: { backgroundColor: 'red' } })

// we can concatenate their styles passed through the style prop onto our existing styles (it can take an array)
// it works like object assign so whatever is last is what is rendered
<ColoredDiv style={{backgroundColor: 'blue'}} />
// div will render blue
```

**Comment by rgbkrk** [comment]
> After the provider refactor, I think we should spend some time making our components more composable.

Totally agree.

> For example, we embed the StatusBar into the Notebook but what if the end user wants to embed their own status bar?

Yeah I think the status bar will probably be way different for a web app. I'm guessing the `<Notebook />` component shouldn't even have the status bar - it should be some higher component up that looks more like this for the opinionated electron notebook (note: as structure, not as the actual components):

```
<App>
  <Notebook />
  <StatusBar />
</App>
```

The pinned cell(s) could be outside of `<Notebook />` here too. As long as configuration is composability rather than inheritance (yay for functional principles that React leans towards) then I'm happy (you can easily get me to rant about ultra-configurability).

**Comment by rgbkrk** [comment]
I'll have to spend some time learning about how we'll package / use CSS in that way. I've been really happy with our theming stylesheets and have lately wondered how we're going to expose the current styles in a good way.

**Comment by theengineear** [comment]
@rgbkrk just catching up on this issue and trying to get some bearings. I'm mostly just trying to learn more about how the repo is organized and such.

## Some responses

>Precursors > Refactor components to remove Redux logic

If I'm understanding this right, you're looking to pass down `dispatch`-y props to child components? I've found that using [`connect`](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) and just defining `mapStateToProps` and `mapDispatchToProps` liberally helps keep logic inside the file you'd *like* it to be in. I.e., if you end up interacting with a component and something breaks, it's more likely that the problem is *in* that component file. I also prefer this for tests. Anyways, just some thoughts.

>We should also think about integrating our CSS into JS to allow users to pass in custom styles through a style prop that will override our defaults.

I wonder if in-lining styles will couple React code a little too tightly with the style? I'm not sure how you're planning on doing the overriding of things, but a well-organized set of scss files (using the 7-1 pattern https://sass-guidelin.es/) can be pretty clean! That said, I've never actually *tried* doing css --> js and have blindly followed [articles like this](http://jamesknelson.com/why-you-shouldnt-style-with-javascript/).

## Extras

Also, you'd mentioned something about creating menu mocks / components. Is the intention to create this from scratch (at some level), or just rely on some [3rd party menu](https://github.com/vkbansal/react-contextmenu)?

**Comment by rgbkrk** [comment]
> you're looking to pass down dispatch-y props to child components

Yep, that's what folks are currently tackling as PRs for https://github.com/nteract/nteract/issues/1288.

> I wonder if in-lining styles will couple React code a little too tightly with the style?

I'm a little afraid of this too, though I think it's not a decision that will paralyze us. We can always change it again later as many of these function more like a library than a site we run. The pressures will likely come from us using nteract components in different fashions.

> Also, you'd mentioned something about creating menu mocks / components. Is the intention to create this from scratch (at some level), or just rely on some 3rd party menu?

If the 3rd party menu works, I'd much prefer to rely on something well supported by others. 👍 As long as we can style it similarly to the rest of our theme(s), branding, and experience I'm certainly game.

**Comment by rgbkrk** [comment]
Ah, I see you linked a context menu (amusingly, we did use this one a few months ago). The menu mocks I'm talking about are top level app style for documents:

### Jupyter

<img width="568" alt="screen shot 2017-01-18 at 9 26 49 am" src="https://cloud.githubusercontent.com/assets/836375/22075276/45f658a4-dd60-11e6-8d67-a79c29e0b40b.png">

### Google Docs

<img width="667" alt="screen shot 2017-01-18 at 9 27 22 am" src="https://cloud.githubusercontent.com/assets/836375/22075297/5af020e6-dd60-11e6-97d9-53104dce37b3.png">

Alternatively, there's the sidebar nav approach:

### Databricks

<img width="707" alt="screen shot 2017-01-18 at 9 28 15 am" src="https://cloud.githubusercontent.com/assets/836375/22075344/858ae0b6-dd60-11e6-8256-261feffd55b6.png">

**Comment by rgbkrk** [comment]
Quick mock for nteract:

![nteract web app](https://cloud.githubusercontent.com/assets/836375/22088196/25797b24-dd97-11e6-85f5-fbfa7a782488.png)

I'll post a Sketch file from that to https://github.com/nteract/mocks as well as one for the dashboard view.

**Comment by rgbkrk** [comment]
As promised: https://github.com/nteract/mocks/pull/14

**Comment by theengineear** [comment]
Re: [top-nav or side nav](https://github.com/nteract/nteract/issues/1346#issuecomment-273542641), I definitely think top-nav is the way to go. I feel like horizontal space is always at a premium when I'm in a notebook.

**Comment by theengineear** [comment]
>If the 3rd party menu works, I'd much prefer to rely on something well supported by others.

👍 👍 I think requirement here should be reasonably simple, I'd be surprised if an acceptable solution doesn't exist.

**Comment by rgbkrk** [comment]
Just an update -- there is now a web version of nteract that runs on top of the jupyter server. You can [try it out on binder!](https://mybinder.org/v2/gh/nteract/vdom/master?urlpath=nteract/edit/example-notebooks)

The jupyter extension is called `nteract_on_jupyter` on PyPI and there are install instructions here: https://github.com/nteract/nteract/tree/master/applications/jupyter-extension
