### ISSUE TITLE
Shift-Tab Behaviour

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1430]
Whilst #1424 fixed the tab behaviour for indenting a selection, on the latest master (`v0.0.15-317-g935444c6 `) the inverse operation shift-tab doesn't work to dedent the selection

The behaviour in the current notebook is for tab to indent the selection 4 spaces and shift-tab to dedent 4 spaces. It would be great if the shift-tab operation were also implemented in nteract.

The GIF below shows the behaviour of nteract master vs the notebook:
![tab2](https://cloud.githubusercontent.com/assets/881019/22716447/cfc31d38-ede1-11e6-9a5f-ac23cdce6a29.gif)

**Comment by peggyrayzis** [comment]
Thanks for opening this, I really appreciate how detailed your bug reports are! 😀 

The default behavior for Shift+Tab is a little weird in Codemirror. It will de-indent up until the beginning of the proper indentation for that code block. I'm not well versed in Python, but I'm assuming that the for loop in your gif created a new code block, which is why you can't de-indent there. Here's a JS example so you can see what I mean - the curly braces indicate a new code block.

![nteract shift tab](https://cloud.githubusercontent.com/assets/18017067/22718748/058d2962-ed70-11e6-8973-ec7a42ab7623.gif)

I'm in support of overriding the default Shift+Tab to match the Jupyter notebook so the user experience is consistent. @rgbkrk what do you think?

**Comment by rgbkrk** [comment]
Overriding the default shift+tab to match the jupyter notebook sounds good to me. Based on how you did the tab override, I think I might try adding in jupyter's introspection API right after your PR.

**Comment by dhirschfeld** [comment]
I think codemirror is perhaps trying to be too smart here. Whilst in some situations it might be nice for the selection to be aligned to the *"correct"* indentation level, sometimes that's not what you want.

I think the simpler rule of increase/decrease the existing indentation of each line by 4 spaces would give a better UX not the least because it's very easy to reason about what the result will be!

**Comment by peggyrayzis** [comment]
Awesome, thank you both for your feedback! I'll have a fix up shortly.
