### ISSUE TITLE
Change in behavior for Markdown Cells

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1444]
When "shift-enter"ing through a notebook I noticed that Markdown cells automatically enter edit mode rather than view. That differs from Jupyter behavior. Is this good, bad, ugly?

**Comment by dhirschfeld** [comment]
I hadn't noticed the difference in handling markdown cells but I just gave it a go and it doesn't really bother me - pressing shift-enter will continue to execute and move down so it doesn't break up my workflow.

It seems this difference is perhaps driven by the fact that nteract doesn't have the command/edit mode distinction so it might actually be strange if it were changed so that you have to press enter a second time to actually edit the markdown cell. It make sense in the notebook because shift-enter puts you in command mode and the second enter changes you to edit mode.

I have no strong opinions on the matter though...

**Comment by rgbkrk** [comment]
Ok I think I'll let it be and ship a release tonight then. :)

**Comment by ivanov** [comment]
I noticed this behavior and find it 👎 for executing through narrative notebooks. 

As @dhirschfeld mentioned, a dual mode would help with this, but I'm aware that I'm speaking as a dual-mode junky.

**Comment by rgbkrk** [comment]
It's disconcerting for me while I'm working through current notebooks, I find it rather distracting and it ends up taking up more vertical space. ctrl-enter also doesn't work to switch it back to view mode.

It also breaks up/down handling in the notebook.

**Comment by jdetle** [comment]
This is definitely buggy, the renderedKeyDown switch statement doesn't actually register the up and down arrow events, for example. I am going off to see _John Wick, Chapter 2_ right now, but I'm going to try and refactor this stuff to clean up dead code later and fix the UI/UX issues.

**Comment by rgbkrk** [comment]
This was fixed up in the 0.2.x line.
