### ISSUE TITLE
nteract as a quiver replacement

### ISSUE THREAD

**Issue by ytjohn** [nteract/archived-desktop-app#1448]
On macOS, I use a program called [quiver](hhttp://happenapps.com/#quiver), which promotes itself as "The Programmer's Notebook".  It has a number of features that make it rather nice for my day to day work. However, it is a macOS only application.  I recently came across nteract and tried it out. I think that nteract (with its ability to run code) could become an upgrade to quiver, if it took on a few features.

Vocabulary: What quiver calls a note is what nteract or jupyter would call a notebook.  A note supports rich text, markdown, latex, and code cells.  What quiver calls a notebook is more like what most apps would call a folder.

Features that make quiver my daily driver:

**Auto-save:**

All notes/notebooks are saved in one location, automatically. As soon as I create a note, it is saved. I don't have to select a location on my file system and give the note a name. If something comes up, I just create a new note. Every note I make is automatically saved in the "inbox" folder, and I can move it to another folder to categorize. I can also add tags to these notes.  I do a lot of "work logs" in markdown cells, and I put code snippets in all over the place. When I open quiver, all of the notes I've created are listed and available. 

Switching to having a single save directory might be a negative for some people ("I want to store my notebook with the larger project I'm working on!"), but I think the automatic saving and collection will be a welcome addition for a lot of people. As long as you can still save individual notebooks in custom directories, no functionality would be lost.

**Organizational Columns**

This goes along with auto-saving in one location. Quiver has a list of "notebooks" and "notes" on the left, and you can sort them by title, creation date, or updated. 

**Searching:** 

For all the notes that quiver knows about, it can do a full-text search of them. If nteract would default save all of its notebooks into a common location, it could perform searches across them. 

**Global Hot Key**

This might be difficult to implement across multiple platforms, but I have a key combo to enter a single note, and another one to bring up the entire collection of notes.

**Comment by rgbkrk** [comment]
Ooooh, neat. Thanks for raising this issue!

I think something like quiver could certainly be built with nteract's packages. I say it that way because core to the current nteract desktop app's philosophy is that we work with documents on disk (to saved locations). This also has an impact as the running kernel's current working directory is supposed to be the same directory the notebook is stored in. Now to respond to specifics.

Yes! We should totally do autosave, also posted in #814.

> Every note I make is automatically saved in the "inbox" folder, and I can move it to another folder to categorize. I can also add tags to these notes.

This cross over from hierarchical and into tag based indexing is something I want to explore for a web version of nteract (see https://github.com/nteract/mocks/pull/14/files and https://github.com/nteract/commuter for the current in progress). Whether that means in the documents themselves (which can be properly indexed) or a separate running service, I'm not sure. I would hope that the native OS could support this more easily -- it's pretty clear though that the best UI for this will come from within the app.

> I think the automatic saving and collection will be a welcome addition for a lot of people. As long as you can still save individual notebooks in custom directories, no functionality would be lost.

I like this! It would mean we're performing the indexing yet allowing freedom around the files themselves. Yes! I'd love to see this happen in the long term.

Once you have the notebooks indexed, you can certainly set up the organizational columns, allow for full search (since we're indexing them, might as well).

-----

An aside - on the Mac I use spotlight to find notebooks frequently, though we're missing a Quicklook plugin (#305) as well as any way to help macOS with indexing notebooks properly.
