### ISSUE TITLE
nteract at the command line

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#145]
Running the main nteract app should let you specify a file (or possibly many files) opening a Window for each.

```
$ nteract blah.ipynb
```

I'm not sure what running it without arguments looks like. A new notebook?

**Comment by rgbkrk** [comment]
Right now the default is:

```
$ nteract nb1.ipynb nb2.ipynb
```

will open a window for notebook 1 and 2. Without arguments, it opens the intro.ipynb notebook.

**Comment by rgbkrk** [comment]
My thought: no arguments should open a new notebook

**Comment by rgbkrk** [comment]
Flows at the CLI:
- `npm run start` opens a new Untitled notebook
- `npm run start {filename}` will create `{filename}` if it doesn't exist

**Comment by jdfreder** [comment]
Totally agree.  Sorry I didn't respond to this issue earlier, didn't show on my radar for some reason...  Any thoughts about what `npm run start .` should do?  Nothing?  Open all notebooks in the immediate directory?  I guess `npm run start *.ipynb` should open all notebooks in the directory because the os will expand the glob

**Comment by rgbkrk** [comment]
> Any thoughts about what npm run start . should do

O___O Haven't thought about that or the case of any `dir/`.

I think it means undefined behavior, we don't open folders. `*.ipynb` is do-able though.

**Comment by rgbkrk** [comment]
Closing since we have a baseline right now of opening files at the CLI.
