### ISSUE TITLE
How can we handle rendering of large streams of data?

### ISSUE THREAD

**Issue by jdetle** [nteract/archived-desktop-app#1452]
I wrote a gist explaining the problem with streams that we're having. Opening this such that people more familiar with react and jupyter can help explain the problem to me! 

### Q: What is going on under the hood when executing + rendering an output?

From the nteract-front end we send an `EXECUTE_CELL` request. This request gets intercepted by the corresponding RxJS epic, `executeCellEpic`. Tracking down where code is rendered then leads us to `executeCellStream`. From this code we can see that we should investigate `handleFormattableMessages`, where we can see that 4 different jupyter kernel message types are handled by this function: `MessageType(['execute_result', 'display_data', 'stream', 'error'])`.

As we can see from the [messaging spec](http://jupyter-client.readthedocs.io/en/latest/messaging.html#messages-on-the-iopub-pub-sub-channel): streams come from data that would normally be sent to STDOUT or STDERR.  For very large streams, the amount of data being rendered is crashing nteract!

In order to investigate, we can open the current `master` branch of nteract. In one terminal we run `npm run build:main && npm run build:renderer:watch`. In a separate terminal, we run npm run spawn:debug to get a log of redux actions when the dev tools are open. 

From here, we can slowly start breaking nteract with a simple python `for` loop.

First:
```python
for i in range(50000):
     print(i)
```
After executing, opening the dev tools, and inspecting the `APPEND_OUTPUT` action, the logger should show a single append output action with an object:
```
Object
name:"stdout"
output_type:"stream"
text:"0↵1↵2↵3↵4↵5↵6...50000"
```

Lets investigate a second time!
```python
for i in range(80000);
  print(i)
```
Investigating the actions in this case should show two consecutive separate `APPEND_OUTPUT` actions. Each with about half of the data belonging to the final output.

In the case of:
```python
for i in range(1000000):
   print(i)
```
we get a bunch of the append output actions and the notebook is unusable for some time.
In the case of 10 million the app crashes upon attempting to render the data. We can see this by recording the process in the dev tools.

To investigate the issue further we need to look at the reducer for `APPEND_OUTPUT` and the `Output` component in `display-area/output`.

If we put a log in the Output component:
```
  switch (output.get('name')) {
        case 'stdout':
          console.log('rendering std out!!\n')
          return <Ansi>{text}</Ansi>;
```
We get to see whats happening in the case of large text files. The log of the react rendering is registering, but the actual act of rendering is not finishing before 
another APPEND_OUTPUT action comes in. This work keeps piling up, and none of the original views are getting shown. One would think that we should be able to get some performance gain by efficient diffing and merging of the VDOM from React. If we have someway of tracking that the rendering is done, and communicating that back to the executeCellEpic, I would think that we should be able to fix this problem. If anyone has any other ideas of what may be going on/ how to fix this, please help me out here!

**Comment by jdetle** [comment]
I think it may be worth considering other ways of handling output data in terms of the react component it is a part of? Possibly worth rethinking `reduceOutputs`?

**Comment by rgbkrk** [comment]
It's worth acknowledging that there will always be an upper limit to the velocity and volume of messages from the kernel that we can handle on the frontend. Same goes with the size of the notebook document. There's some practical upper bound in which we can say "yes, we should be able to handle this much data" and above that limit figure out a way to gracefully fail (as much as we can).

This is, at its heart, an optimization and UX problem for us. It would help to learn how to measure our code to find out where it's taking the most time and if there's anything that can be done. Chrome (and by extension Electron) have [tools to profile code](https://developers.google.com/web/tools/chrome-devtools/rendering-tools/) and there are [good blog posts](http://www.brendangregg.com/flamegraphs.html) [out there on generating and interpreting flame charts](https://addyosmani.com/blog/devtools-flame-charts/).

It would also be wise to read about [Backpressure and node](http://engineering.voxer.com/2013/09/16/backpressure-in-nodejs/) as well as backpressure within Rx - https://github.com/ReactiveX/rxjs/issues/71.

Since some of your questions involve React's own rendering, read up on [React's design principles, particularly Scheduling](https://facebook.github.io/react/contributing/design-principles.html#scheduling). It explains a bit on how it chunks work, in particular:

> If data is arriving faster than the frame rate, we can coalesce and batch updates. We can prioritize work coming from user interactions (such as an animation caused by a button click) over less important background work (such as rendering new content just loaded from the network) to avoid dropping frames.

**Comment by jdetle** [comment]
^ This response is extremely thorough and helpful, thanks.

**Comment by lgeiger** [comment]
With the React 16 release we might be able to revisit our strategy here.

**Comment by rgbkrk** [comment]
You're right!

**Comment by rgbkrk** [comment]
Now that I've done a bunch of refactoring work on our streams in #1998, I think I'm ready to use [`bufferTime`](http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-bufferTime) to batch output updates together, letting the reduction happen on the batch instead of a single output each time.

**Comment by jdetle** [comment]
^ 😎
