### ISSUE TITLE
Installation failed on Ubuntu 16.10

### ISSUE THREAD

**Issue by pachevalier** [nteract/archived-desktop-app#1457]
I've tried to install the binary file on Ubuntu 16.10. I've got an error due to the dependency to libappindicator1. Should I force the installation of this library ? Is there any other solution ?

**Comment by jarmokivekas** [comment]
@pachevalier  I assume that the "binary file" you've tried to install is the debian package for nteract v0.1.0, is this right?

I'm under the impression that `libappindicator1` is needed, since it is one of the default dependencies that electron-builder includes when creating the debian package.

Could you share how are you installing the package? I've managed to install the package on ubuntu 16.10 both using *Ubuntu Software* as well as the command `dpkg -i nteract_0.1.0_amd64.deb`

@rgbkrk as for #1458, libappindicator1 is a debian package, not an npm one, so these two I think are unrelated.

**Comment by rgbkrk** [comment]
Gah, thank you. I used the wrong issue number.

**Comment by pachevalier** [comment]
I've used the command line : `sudo dpkg -i nteract_0.1.0_amd64.deb`.

**Comment by pachevalier** [comment]
Ok, once I've install libindicator7 and libappindicator1, everything works !
