### ISSUE TITLE
In-App Documentation

### ISSUE THREAD

**Issue by arudhir** [nteract/archived-desktop-app#1504]
With Jupyter in the browser, when I hit command+tab+tab, the documentation gets pulled, and even the values a variable/data structure holds.

Given that this is already implemented in Jupyter, how hard would it be to include it into nteract? I'd be willing to (try to) work on it if this is something y'all want!

**Comment by rgbkrk** [comment]
Our tab completion is currently triggered by `ctrl-space` (manually) and otherwise behaves in a typeahead automatic mode. The reasoning behind this was that tab handling with codemirror was tricky since we also wanted it to respect tabs appropriately. We tinkered with the original Jupyter implementation and decided that it was a lot for us to maintain at the time. That being said, it's certainly open for an enterprising individual to handle.

If you're wanting introspection too, check out the work in progress PR #1488 by @alexandercbooth.

**Comment by rgbkrk** [comment]
<kbd>ctrl</kbd>+<kbd>.</kbd> is the current way we trigger this now, though it definitely needs work. Would you want to help improve it @arudhir?

**Comment by willingc** [comment]
@rgbkrk @arudhir I'm going to close this as addressed. I've also opened an issue to recommend additional documentation of the shortcut. https://github.com/nteract/docs/issues/45

<img width="795" alt="screenshot 2018-12-17 19 49 20" src="https://user-images.githubusercontent.com/2680980/50131025-2479e000-0235-11e9-9293-b53e2686e454.png">
