### ISSUE TITLE
Modular code editor

### ISSUE THREAD

**Issue by fbrundu** [nteract/archived-desktop-app#1537]
Hi,
I have a question about the nteract coding process.

Very often I happen to code a notebook and to build a python module on side of this.
Right now my workflow is to define the methods in a separate cell and then, when they are tested enough I move them to a different file, in which I define the python module to import in the notebook. In this case, I use Neovim as side editor.

My question is, is there in nteract (already or planned) a way to edit the code of the module directly from nteract?
I was thinking something similar to some model-based environment, in which the notebook defines the visual analysis, while the most important "backend" methods are structured in a (e.g. python) module which may be easily updated from nteract, without the need to switch to another editor?

Thanks,
Francesco

**Comment by jdetle** [comment]
Hi Francesco,
This sounds like an interesting problem, but I'm not sure its one nteract can solve. Nteract and all the kernels for nteract rely on the Jupyter messaging specification. My (rather limited) understanding is that the way Python handles package management is different than javascript, julia, and other languages for which there is a messaging-spec adhering kernel. In order to maintain a language agnostic specification, I'm not sure this is a goal of the folks maintaining the specification. Of course, as in all things I'm not super sure, I bet other people have some thoughts on this.

**Comment by rgbkrk** [comment]
Hey Francesco,

We don't currently have a way (or plan to) edit code from non-notebook files within nteract. Right now the pattern is to open a separate editor for scripts. Some productivity changes I _think_ we could make would be:

* a `Show in Finder` option that would open the folder where the notebook is located
* an `Open Terminal Here` option that would open a terminal in the same directory

This doesn't get you quite to editing scripts; I hope it would get you closer to an ideal state because those two we can get done pretty quickly.

/cc @lgeiger - time for term launcher!

**Comment by fbrundu** [comment]
Thanks for the quick replies!
Yes, I didn't think that, being language agnostic, it could be against the specification.
I think the two options that you suggested are the best tradeoff.

Thanks for your work!
