### ISSUE TITLE
Add mime-type to stdout

### ISSUE THREAD

**Issue by ajbouh** [nteract/archived-desktop-app#1591]
The Jupyter protocol seems like it assumes that stdout is always text, but there are cases where you'd like to have rich visualizations that are emitted throughout execution (not just at the end).

For example, TensorFlow visualizations are of binary blobs they call summaries. These summaries are emitted throughout execution (not just at the end). So they’re much more like print statements in other languages, which traditionally go to stdout.

i’m looking to do the same… have these summary blobs be visualized as they arrive, rather than just when the execution result is ready.

@rgbkrk You mused in Slack: "I wonder if thats why stream output in colab has metadata 🤔 "

**Comment by rgbkrk** [comment]
The main way that jupyter does multiple outputs is with [`display_data` messages](http://jupyter-client.readthedocs.io/en/latest/messaging.html#display-data). Roughly, they look like this:

```
display_data.content: {
  data: {
    'text/html': '<b>hey</b>'
  }
}

display_data.content: {
  data: {
    'text/html': '<b>woo</b>'
  }
}
```

Recently, [`update_display_data` was added](http://jupyter-client.readthedocs.io/en/latest/messaging.html#update-display-data) which allows for updating prior displays by way of a `display_id` inside the `transient` field:

```
display_data.content: {
  data: {
    'text/html': '<b>hey</b>'
  },
  transient: {
    'display_id': '1234'
  }
}

update_display_data.content: {
  data: {
    'text/html': '<b>HEY</b>'
  },
  transient: {
    'display_id': '1234'
  }
}
```

It seems like a TensorFlow summary object could end up as a mimetype here rather than going out on the `stream` interface, which lets you emit to same parent message (which goes to a cell in nteract & jupyter notebook).

/cc @craigcitro for thoughts on `stream` messages

**Comment by ajbouh** [comment]
@rgbkrk I'm having some difficulty figuring out whether or not it's legal for `display_data` messages to be returned before `execution_result` messages. My instinct says yes. Is that your understanding as well?

For clarity, is the below an example of a valid exchange?

```
execute_request.content: {
  code: "sayThenYellBoldHey(); [42];"
}

display_data.content: {
  data: {
    'text/html': '<b>hey</b>'
  },
  transient: {
    'display_id': '1234'
  }
}

update_display_data.content: {
  data: {
    'text/html': '<b>HEY</b>'
  },
  transient: {
    'display_id': '1234'
  }
}

execute_result.content = {
  execution_count: 1,
  data: {
    'text/plain': '[42]',
    'text/json': [42]
  }
}
```

**Comment by rgbkrk** [comment]
Very valid. Here's some example IPython code to do it in one cell:

```
import IPython.display as d
d.display(d.HTML('<b>within display data</b>'))
d.HTML('<b>an execute result</b>')
```

The execute result (at least in python) is the last evaluation. You can fire off as many display data messages as you want before an execute result (or even after, really).
