### ISSUE TITLE
Implement Kernel Interruption for Windows

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1611]
It would be very nice to have this feature which is available in the classic notebook.

I've just submitted a calculation with a mistake in it which will take ~15mins to finish :grimacing: so figured I would use my time productively and open a feature request issue!

**Comment by dhirschfeld** [comment]
![image](https://cloud.githubusercontent.com/assets/881019/24644001/87c206ea-1954-11e7-88d9-f25e9375e6aa.png)

**Comment by jhslinkman** [comment]
If I disable this check https://github.com/nteract/nteract/blob/820dfa6991d008dd8edd0503d308181780850841/src/notebook/menu.js#L210 and issue a interrupt kernel action, the kernel process seems to terminate properly for me. I'm using Windows 8.

I'd be happy to test a bit more but I want to check whether there's been any further thought on this since https://github.com/nteract/nteract/pull/526 and https://github.com/nteract/nteract/pull/527.

/cc @captainsafia @rgbkrk

**Comment by captainsafia** [comment]
@jhslinkman: That's interesting. We're terminating the kernel by sending a `SIGINT` signal which Windows doesn't listen to. It seems like the most fool-proof way to issue SIGINT messages in Windows is to use `readline` ala what is being done in [this module](https://github.com/bevacqua/node-sigint/blob/master/src/sigint.js). Let me know if you're interested in taking this one and I can help you submit a PR.

**Comment by jhslinkman** [comment]
Ahh, I think I understand what's going on. Yeah, I'll be happy to take a look.

**Comment by rgbkrk** [comment]
Oh we're using a proper spawner now I can fix this up.
