### ISSUE TITLE
Feature Request: Insert Unicode Symbol

### ISSUE THREAD

**Issue by dhirschfeld** [nteract/archived-desktop-app#1711]
In the classic notebook you can enter latex symbol names and press `TAB` to have the equivalent unicode symbol inserted. This would be nice to have in nteract also.

c.f. ipython/ipython#6380

**Comment by rgbkrk** [comment]
That would be cool, I'd like to see that feature here too.

**Comment by dhirschfeld** [comment]
Pretty low priority I'd imagine but I think it's useful to have an issue to at least record it.

**Comment by dhirschfeld** [comment]
It would still be nice to have feature parity with the notebook/jupyterlab

**Comment by rgbkrk** [comment]
This is reachable today via hitting ctrl-space (that's what triggers our completion).

![screen shot 2018-04-13 at 8 03 27 am](https://user-images.githubusercontent.com/836375/38742364-2d4fc8dc-3ef1-11e8-88c6-b3b7962e5e3b.png)
![screen shot 2018-04-13 at 8 03 29 am](https://user-images.githubusercontent.com/836375/38742365-2de853a4-3ef1-11e8-8145-ae70ae72b2e8.png)

I suppose the real issue here is the supporting of tab for completion (we have an issue somewhere for that...)

**Comment by dhirschfeld** [comment]
Just tested and it works great with `Ctrl-Space` so I'll close this as resolved.

> *I suppose the real issue here is the supporting of tab for completion (we have an issue somewhere for that...)*

I found a couple of issues #963, #1870 - nothing specific about tab-completion.
