### ISSUE TITLE
Feature : Add option to upload to a commuter application

### ISSUE THREAD

**Issue by romans127** [nteract/archived-desktop-app#1859]
Greetings,

I can see the need for a user to upload/deploy their a notebook to a commuter application.
In order to accomplish this we would need updates to both nteract as well as commuter.
- add an endpoint to commuter "optional" to receive the contents of notebook.
- upon receiving the contents, save and store the notebook in a designated folder. 

Please let me know your thoughts or plans for this type of feature.

**Comment by rgbkrk** [comment]
Strongly in favor of this. I've been doing a bit of thinking on this, talking to @ewmassey and @adparker.

I'll describe this on a components level (per project / concept), then we can tie it all together.

## Commuter API Endpoint

Publishing a new notebook (or an old one for that matter) as a new published entity:

```
POST /api/v1/published/
{notebook content, could be similar to the contents API}
```

Response:

```
{
  id: "the-id-of-the-published-document",
  version: "1", # This could be a hash of the notebook too
  url: "", # Path to the notebook, for linking out to
}
```

Publishing a new version of a notebook

```
PUT /api/v1/published/123
{notebook content}
```

Response is similar to the POST

## Notebook metadata

A published notebook updates metadata under `.metadata.papermill.publish`

```js
{
  cells: [...],
  metadata: {
    papermill: {
      publication: {
        id: "1234",
        endpoint: "https://mycommuter"
      }
    }
  }
}
```

This captures the endpoint so that publishing again will update the published copy, allowing an author to iterate and publish again.

## Clients - nteract, papermill

nteract will include a button to publish, including a way to set up credentials

papermill will have a `publish` command like so:

```
papermill publish myNotebook.ipynb
```

They both modify the notebook in place to include the above mentioned metadata.

## Versioning

In terms of UI on commuter, I want people to be able to:

* Link to a published notebook
* Link to a specific version of a published notebook (by hash or version number)
* Publish from the commuter browsing interface straight to published

## Opinions on getting started with storage and indexing

In terms of storage and indexing, I'd imagine we could start off by storing the notebook blobs in S3, relying on Object versioning

<img width="725" alt="screen shot 2017-08-21 at 10 30 57 am" src="https://user-images.githubusercontent.com/836375/29531114-f1089c94-865b-11e7-80c4-6f20e0baf873.png">

**Comment by rgbkrk** [comment]
For ease of use, I'd assume that we'd create a dotfile for papermill / commuter that would have their default endpoint and any other information. Auth details should get stored in keychains properly. The key goal here is to make it easy on users for the long term. 😄

**Comment by romans127** [comment]
This is a great spec . 

In regards to versioning and publishing.  What would you think about leveraging git and gist for versioning ?

**Comment by rgbkrk** [comment]
I'd certainly be a fan, so long as we can swap out backends. I don't _really_ want to deal with nonlinear histories of these notebooks (otherwise they should be using git directly), which is why I want to have a single linked list.

How do you want to handle git as the backend for this? We do support publishing to gists now, we don't store any other metadata to an external service though.

Side note -- I just noticed this great little article on [libgit2 backends](http://blog.deveo.com/your-git-repository-in-a-database-pluggable-backends-in-libgit2/).

**Comment by romans127** [comment]
That's a very good point. Certainly keeping the backends modular is the way to go. 
With that said maybe the first iteration can be simple with the structure you proposed above, then potentially give the option to leverage git. 

I was more so thinking of a way that we can leverage the existing publish to gist option, but somehow also tie that in to what get's pulled into commuter. 

Such as if the user published version 12 , if we could get to the correct notebook, and pass a param of ?version=12 or maybe it would know to pull the contents from gist. and display by leveraging the gist api. 

https://science.ryanwatts.me/view/commuter/testing/demo.ipynb?version=15

That may be too much at one level though.

**Comment by romans127** [comment]
Maybe even add a top level dropdown once you are in the view of a notebook, and the notebook's metadata has an endpoint to a gist. then you could select a different version or commit hash.

**Comment by rgbkrk** [comment]
@MSeal and @cHYzZQo we should set aside some time to evaluate how we'd do versioning and publishing of notebooks, especially as we progress further with scheduling of notebooks.

**Comment by rgbkrk** [comment]
Largely speaking, this functionality moved into nteract/bookstore. Closing this, especially since commuter is outside this repo (and not maintained).

cc @mpacer
