### ISSUE TITLE
Modify configuration folders

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#1873]
Hi, and first of all thanks for this very nice piece of software. 

I'd like to use nteract for my high-school students, however I can't install anything in the windows7 system of my school. I get nteract to work with a python3 conda env locally, however there are 2 folders created in the home directory evrytime I launch it: `.ipython` and `.jupyter`.

Is there any way to specify locations for these folders in nteract?

**Comment by rgbkrk** [comment]
Fantastic, that's great to hear you'd like to use it with your high school students! @willingc and @captainsafia will be happy to hear about this. 😄 

As for the Jupyter directories, nteract adheres to the [Jupyter file paths](http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html) (or at least purports to). You can set environment variables to override `JUPYTER_CONFIG_DIR` for Jupyter and `IPYTHONDIR` for IPython. The second one is created by IPython, not by nteract. There is a difference when running nteract vs. the notebook in a conda environment, since it will use the sys prefix within the conda env.

## Overriding `IPYTHONDIR`

The kernel for the conda environment can set keys in `env`, including where you want the `IPYTHONDIR` to be. Example:

```js
{
 "argv": [
  "C:\/python\/python",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "env": {
  "IPYTHONDIR": "C:\/temp"
 },
 "display_name": "Python 3",
 "language": "python"
}
```

Admittedly I don't know where you'd pick the temp dir or how the paths would look inside the JSON without my Windows machine with me.

## Overriding `JUPYTER_CONFIG_DIR`

The only option I can think of here is to either:

1. modify the global environment variable (this seems rough considering the restrictions on the school systems)
2. create a shortcut to the app that sets the environment variable (at least I think this was available)

## Future

I'm open to ideas for how we could make this easier.

**Comment by ghost** [comment]
Thanks for this detailed answer, I tried to set these env variables from my batch script however this don't seem to work. I need to investigate your method to override `IPYTHONDIR` in the kernel for the conda environment, but I don't know which `json` file it is.

**Comment by rgbkrk** [comment]
> don't know which json file it is.

It should be in a file labeled `kernel.json`, likely inside a `kernels/python/` folder.

**Comment by ghost** [comment]
Ok I found the kernel file for my `python3` env in `Miniconda3\envs\python3\share\jupyter\kernels\python3\kernel.json`, now I can choose  a `IPYTHON_DIR` directory to write in which students can write, so everything is ok for me. I close the issue, thanks very much for your help. But I'd like to open another issue: **Add portable version of nteract** as [Atom did](https://github.com/atom/atom/issues/2939), is it doable?

**Comment by rgbkrk** [comment]
It's probably possible.

**Comment by rgbkrk** [comment]
The files we write out, which don't _have_ to be in standard jupyter folders, though it's really nice if they are:

* `nteract.json` - configuration file for theme (in `~/.jupyter` on *nix)
* `kernel-UUID.json` - the connection file (goes in `~/Library/Jupyter/runtime` on the mac)
