### ISSUE TITLE
Add feature to use mybinder.org in some fashion

### ISSUE THREAD

**Issue by yuvipanda** [nteract/archived-desktop-app#1920]
beta.mybinder.org will soon have a clean API that lets you launch a github repository as a notebook server and interact with the API of this notebook server from other web pages / desktop applications. I think this is a good time to think about nteract integration with mybinder.org!

The simplest first feature might be to allow users to 'launch' a repo from within nteract. This would spin up a notebook server on mybinder, and spawn kernels there for use by the nteract app. This allows users to try out different kernels / repositories without having to set up a local environment.. 

https://github.com/minrk/binderhub/blob/db47ece7a413b1c920a2abbbb796eaa393bb27ed/examples/binder-api.py is example code (in python) on how this API call might work. We expect to have this deployed sometime this week.

**Comment by rgbkrk** [comment]
That is super neat! I'd probably want the nteract frontend locked down a bit more, largely to assume that the kernel is _potentially_ untrusted, since nteract can run anything on a local user's machine. One way of doing that would be to only allow certain media types. Another would be to actively iframe outputs and sanitize markdown completely. Someday I think all of the frontends should end up like that.

Beyond my gut reaction from a security standpoint -- from a UX standpoint this would be super exciting! Launching straight from the app would be a great way to get people started using it without having all the local kernels and dependencies they might need, all while working with a document they can save and version control on their own system.

**Comment by psychemedia** [comment]
From a user perspective, part of a related use case comes from a desire to launch an arbitrary  environment accessed via a Jupyter notebook UI.

The environment may be a custom code envt (apt-get and pip dependencies) or may require access to running services (eg a DBMS, or geo tileserver, or etc etc).

One example launcher I'm aware if is O'Reilly LaunchBot: https://blog.ouseful.info/2017/08/30/oreilly-launchbot-like-a-personal-binder-app-for-running-jupyter-notebooks-and-other-containerised-browser-apps/

**Comment by psychemedia** [comment]
The repo README suggests `We support Jupyter kernels locally on your system and on remote JupyterHubs via Binder.` but I don't see any way of connecting to Binderhub kernels in the desktop app?
