### ISSUE TITLE
Tune our usage of CodeMirror

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#1977]
Steps to reproduce a slow minimal notebook:

* Start a new notebook
* Click in the first cell
* Hold down the down arrow key until you have about 70 cells
* Start typing in a cell
* 😭 

I'd love to see the performance here get better. It might be worth seeing what @williamstein and @haraldschilly have done for [CoCalc](https://github.com/sagemathinc/cocalc).

Note: the above is done with React in development mode and I'm not measuring things directly. There could be other optimizations we can make before touching CodeMirror.

**Comment by rgbkrk** [comment]
In fact, here's the [editor component](https://github.com/sagemathinc/cocalc/blob/488f242fda7ee5edd7d1b4b3fda39cfcfb7048f2/src/webapp-lib/jupyter/edit/js/editor.js) used for cocalc's jupyter implementation. Keep in mind it's AGPL with the caveat that @williamstein tends to be open to relicensing portions of code for reuse.

**Comment by williamstein** [comment]
I wrote a lot of code to make things very fast (e.g., using static rendering for all but the current focused cell).  It worked in that it was fast... but then I (temporarily) gave up and disabled all that code, since it was too much work re-implementing everything myself given my goals/needs. The problem is that codemirrors static html export is missing much of the functionality of codemirror, and the author doesn't want to implement it, so you end up having to reimplement a lot (e.g., line numbers). 

>  @williamstein tends to be open to relicensing portions of code for reuse.

I am very open. (Also, this particular code was 100% written by me without any possible ownership issues from employers, so I definitely CAN relicense anything.)
