### ISSUE TITLE
Enhance commutable API

### ISSUE THREAD

**Issue by Madhu94** [nteract/archived-desktop-app#1989]
Working with ``emptyCodeCell`` and ``emptyNotebook`` was not too hard, but we should expose some functions like ``createCodeCell`` and ``createNotebook``. (I like that ``appendCellToNotebook`` no longer needs a uuid supplied by the user)

**Comment by Madhu94** [comment]
Some functions that would be nice to have - 
1. ``createCodeCell``
2. ``createMarkdownCell``
3. ``getCellById``
4. ``getCellByIndex``  - we have pinned cells and the cells can also be drag/dropped in any order, but I think this could still be a useful method.  I'm sure commutable isn't meant to be tied to nteract.
5. ``isEqual`` - on the notebooks. I believe jupyter's ``nbformat`` module does something like this, when checking for trusted/untrusted notebooks it computes the hash of the notebook ( with all the metadata popped off ).  Might also make commutable easier to test.

**Comment by Madhu94** [comment]
I guess I'm pushing my luck with Number 5.

**Comment by rgbkrk** [comment]
You're not pushing your luck on number 5. It mostly depends on what kind of "equality" you want. You can do direct equality between two notebooks made with commutable using [Immutable's `isEqual`](http://facebook.github.io/immutable-js/docs/#/Map/equals):

```
notebook.isEqual(otherNotebook)
```

or

```
Immutable.is(notebook, otherNotebook)
```

This is a fast O(1) computation because it's checking the hashCode between the two objects. It has some caveats to it though:

* The notebook itself needs to be a fully immutable object for this to be accurate
* This is useful for in-memory comparisons (has the notebook changed), not for comparing two notebooks on disk

Generally speaking, `commutable` is a utility wrapper around `immutable` setting up an opinionated data structure. What we probably need to do is link out to `Immutable` docs more. With that, I'll answer a few of the others:

```
function getCellById(notebook, id) {
  return notebook.getIn(['cellMap', id])
}
```

```
function getCellByIndex(notebook, index) {
  const id = notebook.getIn(['cellOrder', index]);
  return notebook.getIn(['cellMap', id])
}
```

Those would probably be fine to add to commutable itself. They're definitely useful for testing, though I imagine I probably wouldn't use them in applications built on top of commutable because I tend to use `updateIn` for performance when I have multiple operations on the document.

> I'm sure commutable isn't meant to be tied to nteract.

That's true. Originally it got built well before the desktop app, it was the start of opinions for what the in-memory data structure would be. I've been thinking on how I would use just the cells from commutable for things like https://github.com/nteract/nteract/pull/1986 or even dashboard / grid layouts.

**Comment by Madhu94** [comment]
We _could_ do pretty much everything with commutable and immutable.js today. It would be nicer to have more abstract functions though (as you noted in another ticket, like nbformat)

**Comment by rgbkrk** [comment]
I think, now that records have gotten a lot better, we should switch to using `Record`s for the core notebook format like in #2742

**Comment by rgbkrk** [comment]
I think this is in a much better state now that commutable is fully backed by records.
