### ISSUE TITLE
Customize tabs indent

### ISSUE THREAD

**Issue by fbruetting** [nteract/archived-desktop-app#2014]
Could real tabs be implemented, instead of just inserting four spaces?

**Comment by rgbkrk** [comment]
Old discussion for tabs & spaces is here: #1238, #1261, and #1256. We have the default set to 4 spaces for the sake of keeping the Python consistent with PEP8 (I might even so far as to say we'd adopt `yapf` for Python).

For javascript, I'd prefer it was two spaces. Since I don't like going back and forth on these though, I'd prefer we stuck with something like `prettier` for autoformatting of JS.

What _I_ need though is someone would take up the mantle of codifying our config setup for codemirror, implementing it, and maintaining it. We have a config setup that is persisted, it requires some tying things together to get the options you want though.

**Comment by fbruetting** [comment]
Can’t that be set by the user individually, instead of applying all the different coding styles? When I code some Rust, some C and some Julia, I don’t care about each one’s code style, but just use my own consistently.

**Comment by rgbkrk** [comment]
Sure! That could be set by the user individually. We'd need someone to implement it and maintain it.

**Comment by andrewfogg** [comment]
This would be great, especially useful when copying pasting code from nteract to IDE or text editor.

**Comment by captainsafia** [comment]
We now support fully customizing the configuration for the CodeMirror editor so this can be closed.

**Comment by everdark** [comment]
Is there a document on the configuration parameters?
I have difficulty finding anything related to indent size.
Here is the configuration doc: https://docs.nteract.io/desktop-config/

**Comment by captainsafia** [comment]
@jeromefv Adding this to your radar as something we're missing docs on.
