### ISSUE TITLE
Kernel Issues

### ISSUE THREAD

**Issue by jameschartouni** [nteract/archived-desktop-app#2054]
I created a new kernel to run tensorflow. When I run the kernel on the command line, or in jupyter notebook, I can import tensorflow without issue. On a Windows 10 version of nteract I get this issue: "ImportError: Could not find 'cudnn64_6.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable." Could nteract be interfacing with the ipython kernel differently?

**Comment by rgbkrk** [comment]
nteract does interact with the system differently than jupyter. We launch a subprocess directly based on what's in the `kernel.json` that goes along with your kernel. This isn't a Python process doing the launching nor started from your terminal so it doesn't pick up your defaults. 

In order to fix this for your system, add the path to `cudnn64_6.dll` in your [`%PATH%` environment variable on Windows.](https://www.computerhope.com/issues/ch000549.htm)
