### ISSUE TITLE
[desktop] Setup webpack live reloading

### ISSUE THREAD

**Issue by lgeiger** [nteract/archived-desktop-app#2328]
We should take a look at https://webpack.electron.build/ on how to setup full webpack live reloading for the desktop app.

**Comment by rgbkrk** [comment]
If that works, awesome! Otherwise, since we have a pretty custom setup now and it works pretty well, I think what we'd need to do is:

* figure out how to run the webpack dev server with our setup
* modify the index.html template to check for the webpack dev server, only checking for it if we're clearly running it in dev mode
