### ISSUE TITLE
Request for inclusion

### ISSUE THREAD

**Issue by paulnakroshis** [nteract/archived-desktop-app#2484]
In the Jupyter Notebook, I recently found a way to number LaTeX equations.
(from this thread: https://stackoverflow.com/questions/41241984/equation-numbering-in-jupyter-notebooks)

Three commands must be entered in a terminal :
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable equation-numbering/main

(I had to become su on one of my Macs to execute the last two lines) 
You can see an example notebook at http://people.usm.maine.edu/pauln/physics261/assignment03_6_feb_2018.ipynb

Would be great if this could be added to nteract!
@captainsafia @rgbkrk

**Comment by captainsafia** [comment]
Hi @paulnakroshis,

Thanks for opening this issue!

Unfortunately, the Jupyter extension architecture doesn't translate well into the nteract desktop application.

In order to add the feature that you're looking for, the MathJax instance within nteract will need to be reconfigured to set the `equationNumbers.autoNumber` attribute.

If you'd like to submit a pull request for this, I'd be glad to help you figure out what would need to be done!
