### ISSUE TITLE
stdout and stderr streams should be accumulated

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#249]
jupyter notebook:

![screenshot 2016-03-22 23 19 25](https://cloud.githubusercontent.com/assets/836375/13975550/8e0dd6a4-f084-11e5-9fe7-129918328bf4.png)

**Comment by rgbkrk** [comment]
Ah, unless broken up by display data:

![screenshot 2016-03-22 23 24 39](https://cloud.githubusercontent.com/assets/836375/13975613/3fdab55a-f085-11e5-900e-0447d1ae993d.png)

**Comment by rgbkrk** [comment]
We currently do an overall reduction on the outputs for all the relevant message types:

``` js
    // Handle all the nbformattable messages
    subscriptions.push(childMessages
         .ofMessageType(['execute_result', 'display_data', 'stream', 'error', 'clear_output'])
         .map(msgSpecToNotebookFormat)
         // Iteratively reduce on the outputs
         .scan((outputs, output) => {
           if (output.output_type === 'clear_output') {
             return new Immutable.List();
           }
           return outputs.push(Immutable.fromJS(output));
         }, new Immutable.List())
         // Update the outputs with each change
         .subscribe(outputs => {
           subscriber.next(updateCellOutputs(id, outputs));
         })
    );
```

whereas it seems like we'll need to do a scan on `stream` that merges in selectively _or_ we reduce prior outputs delimited by display_data.

**Comment by rgbkrk** [comment]
Ok, I find it a little odd that stderr is always on the bottom...

![screenshot 2016-03-23 00 57 05](https://cloud.githubusercontent.com/assets/836375/13976913/20307304-f092-11e5-89c8-c5cd0e82503d.png)

**Comment by minrk** [comment]
the output order is based on message order, which corresponds (in IPython) to the order of `flush` calls. If there's pending output still waiting when a cell finishes, IPython calls:

``` python
sys.stdout.flush()
sys.stderr.flush()
```

If you call flush yourself, you can influence the order:

<img width="384" alt="screen shot 2016-03-24 at 13 39 07" src="https://cloud.githubusercontent.com/assets/151929/14017181/f0e005d0-f1c5-11e5-8b7b-4c6e29798ae7.png">

ipykernel 4.3 flushes asynchronously, so you will get some time-sensitive ordering if there's enough time between writes:

<img width="346" alt="screen shot 2016-03-24 at 13 39 11" src="https://cloud.githubusercontent.com/assets/151929/14017212/1e5d595e-f1c6-11e5-9511-4110deff23ff.png">

Which also demonstrates that we don't merge the streams, so there's a newline on every switch because we put each stdout/stderr switch in divs. This is not an accurate representation of stream output in a terminal, so if you wanted to do a better job, you could do something with spans for the switch instead of divs. Alternately, you could completely ignore the difference between stdout and stderr, which is what a terminal does.

**Comment by rgbkrk** [comment]
Thank you for the feedback Min!

This at least makes me feel better about aggregating according to whichever came first. I was aiming to be as close to the notebook as possible while handling ANSI escape codes properly.

> Alternately, you could completely ignore the difference between stdout and stderr, which is what a terminal does.

This made me curious about escape codes and how they're handled when mixed between stderr and stdout. Of course it's literally what you said. Example script:

``` python
from colorama import Fore, Back, Style
import sys

sys.stderr.write(Fore.BLUE + 'blue!\n')
sys.stderr.flush()
print(Style.DIM + 'STDOUT DIM')
print(Style.RESET_ALL)
sys.stderr.flush()
sys.stdout.flush()
print('back to normal now')
sys.stderr.write('woo\n')
```

Terminal output:

![screenshot 2016-03-24 08 09 27](https://cloud.githubusercontent.com/assets/836375/14017778/e108e0f6-f197-11e5-8d10-78ededfa3232.png)

It's super simple to implement merging the streams in the frontend. However, that diverges from the notebook format. I honestly think that we would be able to support more escape codes in the frontend for view; complete with erase, cursor movement (for display), and text attributes.

**Comment by minrk** [comment]
> that diverges from the notebook format

There's two things here:
1. does running the notebook in nteract produce _the exact same notebook_ as the existing notebook app
2. does it produce a _valid_ notebook

I think it is okay to diverge from the existing notebook implementation on some things like this. For instance, the current notebook _chooses_ to merge consecutive stream outputs (from the same stream), but not doing so is perfectly valid, and indeed we made this change in the notebook for performance reasons without changing the notebook format.

In nteract, you could provide merged rendering of stream output by either
1. matching the collation behavior of the existing notebook in the data structure, just merge them for rendering, or
2. actually discarding stderr information, and turn the notebook into purely stdout, matching the primitive behavior of terminals.

My first inclination is toward (1), but if you want to get rigorous terminal-emulation of things like carriage returns (Jupyter's implementation does not behave identically to a terminal), you can't treat them separately at all.

**Comment by rgbkrk** [comment]
> does running the notebook in nteract produce the exact same notebook as the existing notebook app

no

> does it produce a valid notebook

yes

> indeed we made this change in the notebook for performance reasons without changing the notebook format

I'm noticing the same thing, since we have to keep appending strings. It's making me want to explore another model.

The nice thing about semi-rigorous terminal-emulation is that we could reduce the final string to the representation that a terminal would show. This:

```
"\u001b[?25l\u001b[0G▄ ╢░╟\n\u001b[?25h\u001b[1A\u001b[?25l\u001b[0G▌ ╢░░╟\n"
```

becomes (roughly):

```
\"u001b[?25l\u001b[0G▌ ╢░░╟\n"
```

We then get "terminal animations" while the resulting notebook file is more compact (as well as in-memory representation).

**Comment by minrk** [comment]
It would also be cool if you could implement appending output in a way that doesn't require reprocessing the previous output in order to get the state to be correct. In the current notebook, producing stdout with many messages is an $O(n^2/2)$ operation because it has to append the new message, then redisplay the entire stream. I just don't know how to track the terminal state well enough to do that.
