### ISSUE TITLE
Does nteract desktop need to install R and Python firstly?

### ISSUE THREAD

**Issue by ShixiangWang** [nteract/archived-desktop-app#2610]
Hello,

nteract is a great work. I want to use it to teach others programming, thus I wanna make sure if we need install R and Python locally before using nteract desktop version. If not, how can we install packages/modules and manage them?

Thanks.

**Comment by rgbkrk** [comment]
You do have to install R and Python locally (as well as [their kernels](https://nteract.io/kernels)) in order to use those languages with nteract.

Thanks for using it for teaching others programming. Please also contribute to https://github.com/nteract/education to help all educators with tooling and curriculum. 😄
