### ISSUE TITLE
Automatic file association doesn't work on ubuntu 17.10

### ISSUE THREAD

**Issue by lucainnocenti** [nteract/archived-desktop-app#2661]
I just download the AppImage from the website. Running the app for the first time I get asked whether I want to integrate it with the system. I said yes, and now `nteract` appears among the applications and in the context menu in nautilus on ipynb files. However, neither works (while directly executing the app file from the terminal works as intended).

Running the `nteract` launcher that is added in the dash reveals the possible reason: it gives the error 
>Failed to launch nteract
>Failed to change to directory "/opt/nteract/" (no such file or directory)

Indeed, `/opt/nteract` does not exist.

**Comment by jarmokivekas** [comment]
When I originally worked on fixing some of the issues with Linux packages I worked primarily on the `.deb` packages, which worked better than AppImage. I'm also quite ignorant about AppImage in general, I've never really used them much so I didn't debug them much in the first place. 

I just tested it, and can confirm, that the desktop launcher entry does not work currently using AppImage. I have a hunch that the `.desktop` (which defines the application launcher entry) file needs to be different in .appimage and .deb since the way the packages are installed on the system are quite different.

The .deb version of nteract works as expected for me on Ubuntu 17.10. It launches from the dash, and shows up in the context menu when right-clicking .ipynb files. Double clicking opens .ipynb files.

@lucainnocenti You might want to try installing [nteract_0.8.3_amd64.deb](https://github.com/nteract/nteract/releases/download/v0.8.3/nteract_0.8.3_amd64.deb) from the [release page](https://github.com/nteract/nteract/releases/tag/v0.8.3) if you want better integration with the graphical environment.

**Comment by lucainnocenti** [comment]
@jarmokivekas Thanks for the pointers. I'm totally fine with using the .deb installer! I only used the AppImage because that's the (seemingly?) recommended installation medium in the [website](https://nteract.io/).

**Comment by jarmokivekas** [comment]
My understanding is that AppImages have a wider support when it comes to Linux distributions, as their purpose is to be distribution agnostic.

The .deb package work pretty well in my experience, but it may be worthwhile to improve the AppImage packages, and once they work well, maybe even drop support for the .deb. If i remember correctly, and the build system hasn't changed too much, it may be difficult to maintain both package types. This is because the packaging system was not super flexible. If there is only one package type, it should probably be AppImage, so that distributions don't use .deb have a package too.  

But I haven't thought this through very thoroughly yet.

**Comment by rgbkrk** [comment]
Ah! Maybe I should change the site to just link to the page for the installers. If I was on Ubuntu or Debian I'd just use `.deb`. I think I took someone's recommendation of the AppImage and just went from there.

**Comment by retorquere** [comment]
The desktop shortcut offered on first launch of the appimage doesn't work though. It wants a folder /opt/nteract.

**Comment by Jitender47** [comment]
having the same issue.
double clicking on .ipynb opens in gedit. I tried open with nteract but nothing works.

**Comment by gordon-n-stevenson** [comment]
This can be solved by replacing the 'Path' line in the appimagekit-nteract.desktop which points for some reason to /opt/nteract. This is found in your ~/.local/share/applications folder.

Remove it then restart unity or gnome and you'll be fine. I had this issue running the AppImage from nteract v 0.12.3 in Ubuntu 18.04.

**Comment by jarmokivekas** [comment]
If I remember correctly, the .deb installs everything in /opt/nteract, which is why the .desktop points there. Electron-builder (the app packaging system) builds deb,  appimage, and other Linux packages pretty much from the same config file, so there are sometimes some strange side-effects.

double clicking ipynb files works on the .deb,

**Comment by sasasagagaga** [comment]
I have the same issue

**Comment by hakon-j-d-johnsen** [comment]
This issue is bigger than automatic file association being broken. In essence, all the desktop integration is broken in the AppImages (at least when run from distributions such as Ubuntu that don't include AppImageLauncher).

The problem is the `Path: "/opt/nteract/"` setting in [package.json](https://github.com/nteract/nteract/blob/49bb0a5cd4a5c0c756b73cc9e88529ed02b0a1ee/applications/desktop/package.json), which is used when electron-builder creates the .desktop file. Since the AppImage version does not use `/opt/nteract`, this leads to a broken .desktop file.

I don't have time at the moment to set up a proper environment to test this and provide a pull request, but it should be relatively easy to fix:

Do the .deb/.tar.gz versions really need to be run from the `/opt/nteract` directory to work properly?
 *  If no: Remove the Path setting from package.json, and everything should work for all targets: https://github.com/nteract/nteract/blob/49bb0a5cd4a5c0c756b73cc9e88529ed02b0a1ee/applications/desktop/package.json#L93 
 * If yes: Add a separate "AppImage" key to [package.json](https://github.com/nteract/nteract/blob/49bb0a5cd4a5c0c756b73cc9e88529ed02b0a1ee/applications/desktop/package.json), with the identical `desktop` configuration as the one under the `linux` key, except without the `Path` setting.

I consider this to be fairly important to fix, especially since AppImage currently seems to be the default version provided when visiting https://nteract.io/ while running Linux.

**Note:**
This issue will also go away as soon as your build system is updated to electron-builder version 21 or later, due to the removal of desktop integration as described in their [documentation](https://www.electron.build/configuration/appimage). Until that time, however, it would be great to fix this issue to stop installing broken .desktop files to people's systems.

## For other users experiencing this issue:
As  @gordon-n-stevenson mentioned [earlier](https://github.com/nteract/nteract/issues/2661#issuecomment-468503651) in this thread, you can do the following to fix your installation:
1. Remove the line `Path=/opt/nteract/` from your `~/.local/share/applicationsappimagekit-nteract.desktop` file.
2. Restart unity/gnome, or restart your computer.

**Comment by jarmokivekas** [comment]
sorry if I'm repeating myself. I didn't re-read the whole thread... :sweat_smile: 

@hakon-j-d-johnsen I'd say the .deb packages should install in `/usr/share/nteract/` or in `/opt/nteract/` as it is now. It would be great to automatically build Appimages where the path in the .desktop is correctly configured. When configured package.json for Linux (years ago?), I had never used electron-bulider before. I don't think I ever quite figure out a way to build completely correct .deb and .Appimage, since they automatically had the same .desktop file, but "install" in different locations. It might well be possible to do, I just didn't know how to do it. 

I have never had any reason to use Appimages as an Ubuntu user the .deb is a much more natural choice. I've always thought the point of Appimages was that you can run them easily from external media without needing to install anything, so I guess i wouldn't expect them to have any/much os integration such as file association. But I'm not a Appimage user, so don't read too much into what I think of them :smile:

**Comment by hakon-j-d-johnsen** [comment]
@jarmokivekas I realize my question was a bit unclear. When I asked whether the .deb file needs to be run from `/opt/nteract`, I was referring to whether the nteract executable (which is installed to `/usr/local/bin/nteract`) needs to be run with `/opt/nteract` as its _working directory_. In addition, and independently from that question, `/opt/nteract` is also the _installation directory_, which [cannot be changed](https://github.com/electron-userland/electron-builder/issues/805).

I gave it a try myself, by installing the .deb package on my system. It turns out that it does not need to be run with `/opt/nteract` as its working directory. In fact, it is beneficial for it to **not** use `/opt/nteract` as a working directory, because the working directory becomes the place where the `Untitled.ipynb` file is saved. Since a regular user does not have write permissions to `/opt/nteract`, the result is the following error message each time the app tries to autosave: (Clean, fresh .deb installtion in Ubuntu 19.10.  App started from the .desktop entry.)

![image](https://user-images.githubusercontent.com/52157318/72602143-12c2aa80-3917-11ea-8cbd-5f8ec0431ad8.png)

If I remove the Path key (which controls the [_working directory_](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-path)) from the .desktop file, I get the following instead:
![image](https://user-images.githubusercontent.com/52157318/72602506-aac09400-3917-11ea-9a36-3f574cab89ae.png)

According to [electron-builder docs](https://www.electron.build/configuration/linux), the settings under `build -> linux -> desktop` only control the .desktop file, and the Path-key in the .desktop file [only controls _working directory_](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html#key-path)

It should therefore be safe to remove the Path setting from your `package.json`:
https://github.com/nteract/nteract/blob/a0f603a149663cbb49cb86d937526ec147645611/applications/desktop/package.json#L93
