### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by dafuer** [nteract/archived-desktop-app#2688]
Hi,

Just an idea: A very good thing of nteract is that it uses full width of the screen. It would be great to have an option to align the output next to input (instead of below). This feature will be great because when someone is working in produce specific output (for example a plot) you can see code and output at same time (no scroll needed). Also, with that layout, the user can see the results as book pages while in the other column you have the code used to produce them.

Thank you to consider the idea, even if it is rejected :-)

Regards.

**Comment by qzcool** [comment]
My current temporary solution is rotating the monitor by 90 degrees clockwise...

**Comment by rgbkrk** [comment]
Wait do you really rotate your monitor for that? 😄 

Having code and outputs appear side to side is an interesting idea. I haven't thought through the implications of it much though (mostly as it relates to being able to set/change this setting on all cells, some cells, etc.). I'll be thinking about it!

**Comment by yozlet** [comment]
I'd also love this feature, especially because it's close to the Swift Playgrounds/"Learnable Programming" view. Is it doable by customising the CSS, or does it need more than that?

To start with: just having the row unconstrained in height would be great as is.
(There would be open questions/possibilities about how tall a row should be: for me, I'd love to be able to limit the row to the height of one sub-cell (i.e. code or output) and constrain the other sub-cell to that height (by resizing a graph, or making it scrollable, or whatever). Anyway, this is all for later enhancement.)

For more horizontal layout options, check out Apache Zeppelin. I don't think it currently lets you put code and output side by side, but it does have some nice features for laying out multiple cells horizontally and constraining row/cell height.
