### ISSUE TITLE
Add new .ipynb file by right clicking on the folder directory

### ISSUE THREAD

**Issue by qzcool** [nteract/archived-desktop-app#2780]
I am not sure if this should be a core functionality of Jupyter working with OS. It is convenient and user-friendly for new users who are used to create new files by right-clicking.

**Comment by Ankk98** [comment]
@qzcool 
I would like to work on this functionality.
Can you guide me on this?

I think we need to work separately for windows, osx, various Linux based os.

I would like to start with ubuntu 18lts.

**Comment by Ankk98** [comment]
https://askubuntu.com/questions/88480/adding-extra-options-to-right-click-menu#88485

But how can we add a functionality so that such a menu is added when we install nteract in ubuntu?
Also, there can be different desktop environments, different versions of operating systems have different features for e.g. https://itsfoss.com/add-new-document-option/

I think this can be done easily on windows as it has this functionality inbuilt.

**Comment by jameskoch** [comment]
Take a look at [Electron](https://electronjs.org/); most of nteract's desktop integration features come from there.

**Comment by jibraniqbal666** [comment]
I want to work on this, please tell me if someone is not working on it.

**Comment by captainsafia** [comment]
Hello @jibraniqbal666! You're definitely welcome to work on it as a pull request for this effort has not been opened yet.

To get started, you can follow the instructions in our [contributing guide](https://github.com/nteract/nteract/blob/master/CONTRIBUTING.md) to set up a local instance of nteract for development.

**Comment by captainsafia** [comment]
We should still tackle this.

Because of OS limitations, this is something that we can only do on the Windows context menu. Not sure if it is feasible on Linux but have verified that macOS doesn't support this feature.

To get this working in Windows, we'll need to add some logic that registers metadata to the Windows registry on app launch.
