### ISSUE TITLE
Duplicate characters with Julia autocomplete

### ISSUE THREAD

**Issue by atbug** [nteract/archived-desktop-app#2929]
I am using IJulia with nteract 0.8.4 on windows. Here are some issues I have encountered:

1. Autocompletion types the entire word again instead of complete the word:
![image](https://user-images.githubusercontent.com/8522036/40708757-d84ec378-6426-11e8-93bc-8e3c1703a03f.png)
After hitting tab:
![image](https://user-images.githubusercontent.com/8522036/40708768-e0cc8210-6426-11e8-911d-604b4092a5fd.png)

2. Unicode typing does not work. Is this related to the fact that IJulia kernel completes the unicode itself?

These issues do not appear with `ipython`. Therefore I guess this is easily fixable?

Thank you.

**Comment by rgbkrk** [comment]
Yikes!

We have one muscle memory mismatch which is that we don't use the tab backed implementation in nteract. It's ctrl-space to trigger manually (otherwise it comes up automatically) and enter to pick.

Thank you for logging this so we can revisit this and refine the autocomplete UX.  🤗

**Comment by atbug** [comment]
These issues are still there if I use enter instead of tab to pick.

**Comment by bit-player** [comment]
This problem has made nteract unusable with any version of Julia later than 0.5. (The current release is 1.0) It's not just on Windows and it's not a matter of keybindings. Any user action that accepts the autocomplete suggestion (Enter, Tab, right arrow, mouse click) triggers the bug. "func", for example, completes to "funcfunction".

It appears that between Julia version 0.5 and version 0.6 there was a change in the format of autocomplete information supplied by the IJulia kernel, and nteract is having trouble digesting the new input.

I'd really like to get this problem fixed, and I'm willing to try it on my own, although it doesn't look like an obvious task for a newbie. Would anyone be able to help me get started?

**Comment by rgbkrk** [comment]
Thank you for having the patience to try to fix it @bit-player. I'm happy to help you get your development copy of nteract running to see what's going on.

You'll need both [`yarn`](https://yarnpkg.com/en/docs/install) and [`node.js`](https://docs.npmjs.com/getting-started/installing-node#installing-npm-from-the-nodejs-site) (I recommend using [nvm](https://github.com/creationix/nvm) as your node version manager).

Once that's ready, you'll need to [set up our monorepo](https://github.com/nteract/nteract#set-the-monorepo-up-in-dev-mode), which is how we hack on multiple apps and packages in tandem.

After the repo is set up, you can run

```
yarn app:desktop
```

to build the app all in one. In order to debug this issue, you'll probably want to intercept the messages that come through from the kernel, which might be easiest to do in the editor package `@nteract/editor` is the package and `packages/editor` is the location in the monorepo. There's a bit more detail than that, so let me know if you've got the rest set up and we'll go from there!

**Comment by willingc** [comment]
Verifying that with IJulia v1.0.3 that the autocompletion of a command does leave the entered text and the full repeated command as seen by @mistguy. (Tested on macOS 10.14.2)

**Comment by atbug** [comment]
My recent test with nteract 0.15.0, julia 1.2 and IJulia 1.20.0 shows autocomplete is completely gone.

**Comment by willingc** [comment]
Closing and consolidating all autocomplete issues in #4995
