### ISSUE TITLE
Completion timeout occasionally too aggressive for Almond kernel

### ISSUE THREAD

**Issue by jameskoch2** [nteract/archived-desktop-app#3314]
In general, it would be great if timeouts like this were configurable w/o rebuilding the product.

Using the latest Almond (formerly jupyter-scala) kernel it's easy to spam the Console w/ timeout errors due to the 2s timeout hardcoded here - https://github.com/nteract/nteract/blob/54c50e856930e9489e9b920365dacc3f10320af4/packages/editor/src/jupyter/complete.js#L108-L115

I can collect a histogram of completion times if helpful, but just "feeling it out" at the keyboard the sense I have is that:
1. Most completion requests come back in ~200ms
2. At the start of an expression when the search space is least constrained (ex: "FOOOOOO_" where _ is the cursor) completions regularly take 750-1250ms.
3. Since nteract is attempting completions as I'm typing (👍), the kernel occasionally struggles to keep up (probably queuing them up, though I'm not positive) and the timeouts become common.

It's possible that the kernel could be more intelligent about avoiding nonsense work in this scenario.

**Comment by jameskoch2** [comment]
@alexarchambault might be interested.

**Comment by rgbkrk** [comment]
This is one area where we're not tracking "old" completion requests. In Rx parlance, we should be `switchMap`ping when a new completion request is going to be sent as well as throttling new ones.

**Comment by alexarchambault** [comment]
On the almond side, I've been wanting to look more closely at the completion requests nteract sends to it, but didn't yet… Maybe cancelling (on the kernel side) the currently running completion when a new completion request arrives could help. If that's the case, support for that could be added to almond.

**Comment by jameskoch** [comment]
I've been looking at this. I wanted to explore front-end solutions first, though it might be tricky to keep both fast and slow kernels happy w/ one solution.

The best UX I've been able to obtain involves a debounce on the front end. Any sense if that would be tolerable for other kernels @rgbkrk ? I've been using 200ms which makes a _world_ of difference; I can try ratcheting that down further.

Without some sort of hard-coded debounce, the next best front-end solution I can come up with is capping the number of concurrently active completion requests at one. The downside is that you end up needing to execute two completion requests where one debounced one would have been sufficient. Example:
1. complete("foo.") starts
1. complete("foo.b") encountered; discard since (1) is still running
1. complete("foo.ba") encountered; discard since (1) is still running
1. complete("foo.") finishes; now trigger complete("foo.ba") so we aren't left with non-sense results

For kernel-side solutions, something like switchMap would be perfect assuming the underlying guts (in this case the ammonite REPL) are easily interruptible. @alexarchambault if you know anything about that and can point me to some particular API, I'm happy to take a swing at it from that side.

**Comment by rgbkrk** [comment]
Setting a debounce per kernel seems like the sort of thing we can measure and adapt to while the app is running, possibly having a known debounce level for each main language (Python, R, Scala, Javascript) encoded in the app. Happy to try out `200ms` as a start.

**Comment by jameskoch** [comment]
#3455 does about all I can think to do to mitigate this from the nteract side. Filed [this Almond issue](https://github.com/almond-sh/almond/issues/241) to improve handling in the kernel side.
