### ISSUE TITLE
Send shutdown message when closing app

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3333]
nteract 0.11.6
Windows

When closing the app by clicking the X in the top right corner, I'm pretty sure no shutdown message is sent.

**Comment by rgbkrk** [comment]
Thanks for noting this, I didn't realize we weren't sending the shutdown in our "please kill this kernel immediately because we're closing down the app" logic. That gets triggered here:

https://github.com/nteract/nteract/blob/6658cbd4057621df683e799ea162c20f322df2e7/applications/desktop/src/notebook/global-events.js#L12-L23

If I recall correctly, I ended up just closing the process in an immediate way, because of how [`onbeforeunload` works in Electron](https://github.com/electron/electron/issues/7977). Sure enough, when the kernel is killed with this "immediate" function, the `shutdown_request` doesn't happen:

https://github.com/nteract/nteract/blob/26a6a30bb9ee78713393c455fbdf1a442695e6fa/applications/desktop/src/notebook/epics/zeromq-kernels.js#L335-L341

The reason I went without sending the message is that there is sometimes a chance the shutdown request hasn't been sent, as shutdown is synchronous. If we want to ensure it gets cleaned up we likely have to do coordination with the electron main process or by doing a bit of gymnastics with `onunload` and `onbeforeunload`.

I'm assuming you want to use this to clean up some background resources?

**Comment by jameskoch** [comment]
A particular case where `killKernelImmediately` is too aggressive is on Windows with a kernel launched from a BAT script.  The JS libs involved in issuing SIGKILL terminate cmd.exe (running the BAT script) w/o giving it a chance to shut down the kernel.

I can think of some non-Jupyter-protocol ways for me to mitigate this in the kernel, like monitoring certain pipes or a known parent process id.

FWIW Jupyter notebook sends the message here - https://github.com/jupyter/notebook/pull/3000

**Comment by rgbkrk** [comment]
Oooh, good call. Thanks! 

👀  @BenRussert

**Comment by jameskoch** [comment]
I'm planning to start on this assuming no one else has.

More specifically, I'm thinking of adding this as a `close-notebook` epic in the desktop. First I'll have it integrate w/ the well-behaved `killKernelEpic` that sends the shutdown msgs. I could imagine the same `close-notebook` epic evolving to include the prompt about abandoning unsaved changes, though not holding that level of integration as must-have.

**Comment by jameskoch** [comment]
Fixed by #3402.
