### ISSUE TITLE
Using the notebooks metadata storage for gallery like features

### ISSUE THREAD

**Issue by betatim** [nteract/archived-desktop-app#3354]
When running a notebook gallery it would be cool to show users more information about a notebook than the notebook itself. For example: "last datetime this nb was successfully executed" or "how many likes does this nb have", etc. You could store that in a parallel DB and then display it in commuter. You could also store it in the metadata of the notebook itself. This means we don't need a new DB and figure out a way to link the notebook to its DB entry. Could also make it easier to track this information when I reupload a notebook under a new name.

I've not looked at commuter in a while. Does it already show metadata? Has someone thought about this and figured out it isn't such a smart idea?

**Comment by charsmith** [comment]
I certainly think it would be a good idea.  We currently only show some information about Papermill.  One current consideration about the metadata in the notebook (which is why we haven't pursued this further) is that without concurrent editing, we have been reluctant to add metadata to a file when it is not being executed.

**Comment by betatim** [comment]
Good point with the concurrent edits :-/
