### ISSUE TITLE
MathJax.js loading from Cloudflare in desktop app

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3366]
Observed in both 0.11.6 and 0.11.7 dev tools.

**Comment by jdetle** [comment]
I apologize in advance for my ignorance, but can you help me understand why this is a problem?

**Comment by jameskoch** [comment]
Desktop apps deployed into a corporate environment might not have full and unfettered Internet access. Mostly it's a question of how the desktop app wishes to define it's need for public Internet connectivity; is it clearly required, explicitly not required, or does it vary by feature?

**Comment by rgbkrk** [comment]
For the desktop app it should operate completely disconnected from the internet. It should work on planes, in the jungle, in the savannah, when the power is out, isolated lab environments, any where and any time you're not on the internet.

We have a version of MathJax packaged up for electron we need to integrate, so let's target this for an upcoming release.

**Comment by jameskoch** [comment]
@rgbkrk is your open PR #3384 at all related to this? If not, any tips on how I could resolve this myself? It's blocking some of our testing.

**Comment by rgbkrk** [comment]
I was hoping to finish refactoring our latex setup then go to town on swapping out the latex used with the [mathjax electron](https://github.com/nteract/mathjax-electron) setup. For resolving this, you can use the current LaTeX API and re-integrate mathjax electron. If I recall correctly we switched to the cloudflare version so that we'd have the full config people were expecting in the notebook (as we were minimal, yet divergent from classic).

**Comment by rgbkrk** [comment]
@jameskoch I'll work on this for a couple hours today and likely some on Sunday. I'll keep you posted so this doesn't block you and we have a good path.

**Comment by jameskoch** [comment]
This was fixed a while ago.
