### ISSUE TITLE
Is redux-electron-store used?

### ISSUE THREAD

**Issue by jameskoch** [nteract/archived-desktop-app#3394]
I stumbled upon this, read the manual, and it seems like it isn't really wired up in the renderer processes as described here https://www.npmjs.com/package/redux-electron-store#renderer--webview-process 

Is it just vestigial at this point?

**Comment by rgbkrk** [comment]
It looks like it's only setup for the main process at the moment:

https://github.com/nteract/nteract/blob/master/applications/desktop/src/main/store.js#L3-L20

If I recall correctly, this was done so that we could keep the kernelspecs synced up between main and renderer. Based on `kernel-specs`, I see use of a module level variable being sent around rather than the store, so something is missing here.

**Comment by lgeiger** [comment]
What about removing `redux-electron-store` completely then?

It looks like we don't need it right now for our use case. This would simplify the main process and remove duplicated dependencies in the main and renderer webpack bundles.
