### ISSUE TITLE
Handle ipynb local links directly

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#349]
Clicking a link that resolves to `./foo/bar.ipynb` should open a new nteract window with `./foo/bar.ipynb`.

**Comment by estevanjantsk** [comment]
Trying to figure out how to get the click event of a <a href=""> tag of the latex component ._.

**Comment by rgbkrk** [comment]
Ah, there may be a neat way of [handling this within launch.js](https://github.com/nteract/nteract/blob/751bb0938252d08f9658d0bd0cf68cda5ba93bd7/src/main/launch.js#L31).

**Comment by rgbkrk** [comment]
Right now our function for launching URLs has the native browser open it instead:

``` js
export function deferURL(event, url) {
  event.preventDefault();
  shell.openExternal(url);
}
```

That can do other logic on the passed in `url` to check if it's a local link that ends in `.ipynb`. No messy handling of the links on a page, letting Chromium/Electron just hand you the URL when ready.

**Comment by estevanjantsk** [comment]
@rgbkrk Nice, that method that I was looking for :dagger: . Gonna try to help with this one. May you assign this issue to me, please? :+1: :+1:  enjoying help you, guys. =D

**Comment by estevanjantsk** [comment]
@rgbkrk Do you know why this link './foo/bar.ipynb' reproduces this url? -> file:/Users/estevanj/Documents/Projects/nteract/static/foo/bar.ipynb .. Why goes to the static folder? 👍 But when i put '../foo/bar.ipynb' the url is ok.

It looks like the current folder when you do the ./ is the static folder, is this right?

The current solution I get is:

```
if (url.endsWith('.ipynb')) {
  url = url.replace('file://', '');
  launch(path.normalize(url));
}else {
  shell.openExternal(url);
}
```

Realize that I have to remove the file:// because when it goes to the win.webContents.send('main:load', filename); with the file:// it'll not load properly.

**Comment by rgbkrk** [comment]
We've definitely got a bit of a problem in terms of how electron views the page - we have to track the user's `cwd` while keeping Electron's relative asset loading intact.

Separate from that issue, there is a helper path to finding the relative path: `__dirname`.

For instance, in the main window `__dirname` is `/Users/kyle/code/src/github.com/nteract/nteract/static` for me.

Another note: If we notice the prefix is not `file:` we must do `openExternal`, even if it ends in `.ipynb`.

**Comment by rgbkrk** [comment]
Hmmm, well this is interesting. I may have figured out something wonderful while exploring [the browser window docs](http://electron.atom.io/docs/api/browser-window/). We could set the `open-url` handler in nteract and consistently rely on that for opening `.ipynb` links. This would solve another problem we have with loading relative assets that are next to the notebook.

🤔

**Comment by estevanjantsk** [comment]
Wow, definitely gonna try that one :ok_hand: . Hey, sorry for the delay in responding I work full-time =B (with angular and rails) and I've never ever touch electron and react code before. But I'm trying to do my best o/. Thanks man =)

**Comment by gnestor** [comment]
@estevanjantsk Let me know if I can help with this one 👍

**Comment by gnestor** [comment]
@estevanjantsk Thanks for working on this. However, it's not working as expected for me because `getPath` is resolving URLs to the nteract root (`__dirname, '..', '..',`) but it should be resolving URLs to the notebook directory. In my case, the notebook I'm using is located at `/Users/grant/Sites/jupyter/ipywidgets/docs/source/examples` and the link in it is `Using%20Interact.ipynb` (or `./Using%20Interact.ipynb`). These links should resolve to `/Users/grant/Sites/jupyter/ipywidgets/docs/source/examples/Using%20Interact.ipynb` but instead are resolving to `/Users/grant/Sites/jupyter/nteract/Using%20Interact.ipynb`. 

The question is: Does `deferURL` have access to the path of the "sender" notebook? If so, then `getPath` could look like `path.resolve(path.dirname(SENDER_NOTEBOOK_URL), url)`. Using `path.resolve` vs. `path.join` will handle absolute URLs appropriately.

**Comment by gnestor** [comment]
@rgbkrk Do you have any insights about how to get the CWD of the notebook vs. nteract?

**Comment by rgbkrk** [comment]
When we launch kernels we use `path.dirname(path.resolve(filename))` to get the directory for the notebook.

**Comment by gnestor** [comment]
Hmm, so is it possible to access this path from `markdown-cell.js` for example? The bug here is that clicking a relative link to another notebook inside a markdown cell will open a new nteract window but the url of the notebook is relative to the nteract `static` directory, not the original notebook's directory.

**Comment by rgbkrk** [comment]
State tree wise it's in `state.metadata.filename`. I'm going to try the `<base>` element real quick.

**Comment by rgbkrk** [comment]
I knew this would be a problem for loading our CSS and yet it's also kind of awesome:

![screen shot 2017-02-07 at 3 37 55 pm](https://cloud.githubusercontent.com/assets/836375/22716576/76eb0cf2-ed4b-11e6-8786-e55f38936aee.png)


```diff
diff --git a/src/notebook/components/notebook.js b/src/notebook/components/notebook.js
index b54f201..654f196 100644
--- a/src/notebook/components/notebook.js
+++ b/src/notebook/components/notebook.js
@@ -24,6 +24,8 @@ import {
 } from '../actions';
 import type { CellProps } from './cell/cell';

+const path = require('path');
+
 type Props = {
   displayOrder: ImmutableList<any>,
   notebook: any,
@@ -39,6 +41,7 @@ type Props = {
   CellComponent: any,
   executionState: string,
   models: ImmutableMap<string, any>,
+  filename: string,
 };

 export function getLanguageMode(notebook: any): string {
@@ -64,6 +67,7 @@ const mapStateToProps = (state: Object) => ({
   stickyCells: state.document.get('stickyCells'),
   executionState: state.app.get('executionState'),
   models: state.comms.get('models'),
+  filename: state.metadata.get('filename'),
 });

 export class Notebook extends React.PureComponent {
@@ -211,6 +215,7 @@ export class Notebook extends React.PureComponent {
     const cellOrder = this.props.notebook.get('cellOrder');
     return (
       <div>
+        <base href={`${path.dirname(path.resolve(this.props.filename))}`} />
         <div className="notebook">
           <div
             className="sticky-cells-placeholder"
```

**Comment by rgbkrk** [comment]
Note that the path is still wrong above. I'm mostly convinced there's a way to use `base` really well here to make sure that the notebook treats assets relative to the file itself. What's important here is that our originating assets load from the right location and then everything user generated is according to the `<base href`.

**Comment by gnestor** [comment]
I like your `<base>` idea better, but I got it working for [markdown cells](https://github.com/nteract/nteract/pull/1432).

**Comment by ghost** [comment]
Any progress on this?

**Comment by rgbkrk** [comment]
Are you wanting to work on it @megamindbrian?

**Comment by ghost** [comment]
@rgbkrk I probably can.  
Here are 3 use-cases I could see improvement on:
* Jupyterlab in a web-browser (does loading relative resources currently work?)
* Localhost running jupyter from command-line. (works, but urls have to backtrack to http://localhost:80/root/files/)
* Local file:// loads within Electron and other nteract platforms. (Looks like file:/ opens but is missing two slashes at the beginning, should be file:///Users/.

Can we pull in the other two heads for guidance on how to handle relative URLs to resources?
@blink1073
@minrk

I love using this software so far, this morning I wrote a widget to convert image assets in Gmail attachments in to Angular components. :D

**Comment by rgbkrk** [comment]
The approach I'd like to take is the one outlined above using `<base>`. We're not running a webserver so we have to treat things a bit differently.

**Comment by blink1073** [comment]
Relative resources are loaded in JupyterLab, using the same `/contents` REST API that the Notebook is using.   Agreed with having a different approach for an entirely native app.

**Comment by captainsafia** [comment]
I've implemented this in https://github.com/nteract/nteract/pull/4336 by building on top of the `base` support added in https://github.com/nteract/nteract/pull/4326 and modifying the launch notebook code a bit.

**Comment by gnestor** [comment]
Thanks @captainsafia!
