### ISSUE TITLE
Feature request: nteract to automatically create kernel with default name

### ISSUE THREAD

**Issue by kiwi0fruit** [nteract/archived-desktop-app#3518]
Jupyter notebook automatically has kernel with default name:
```json
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
```
But nteract doesn't have such kernel by default. It would be nive to have some message appear from menu or automatically that shows instruction how to install it in two clicks so nteract would see it (I know that there is a command that can be copy-pasted to CLI with jupyter available).

**Comment by alshain** [comment]
Even worse, for me nteract automatically created a kernel configuration pointing to an nteract virtualenv in the global settings:
C:\Users\Me\AppData\Roaming\jupyter\kernels

Because the kernel was named python3, launching jupyter from any other virtualenv, the nteract kernel took precedence. 

It took me a while to figure out why jupyter's python process (desiredvev/python3) woudl start a subprocessess (nteractvenv/python3) for jupyter notebooks

**Comment by kiwi0fruit** [comment]
@alshain So Nteract does create such named kernel automatically? I guess it didn't create it in my case because it didn't find python or jupyter in my PATH...

And yes - your usage example shows that it's not that simple matter. I guess nteract should create specially named kernel so that it affects only nteract behaviour.

As about my problem: it should give me instructions when nteract was not able to create the kernel automatically. So I for example activated environment and then typed some simple commands.

**Comment by alshain** [comment]
@kiwi0fruit I just checked my version, I was still running v0.4.0 (November 2017). I'm guessing the behavior changed in the mean time.

I never used nteract since then and was pretty confused why my jupyter notebook in a venv couldn't find the python packages that I installed in the same venv. 

I then discovered that jupyter launched a python instance in a nteract venv (that I didn't even know about) and couldn't figure out why that was...

> But nteract doesn't have such kernel by default. It would be nive to have some message appear from menu or automatically that shows instruction how to install it in two clicks so nteract would see it (I know that there is a command that can be copy-pasted to CLI with jupyter available).

Since I installed this a year ago, I can't remember, but maybe I manually created a venv for nteract and installed the python3 kernel, so it would work because there was none by default?

So I may have been a bit quick to blame nteract for that.

**Comment by alshain** [comment]
So, I just updated to the latest version (0.12.3)

No python3 kernel appeared. 

The documentation on https://nteract.io/kernels/python suggests to run:

```sh
$ python -m ipykernel install --user
```

Turns out this was probably the culprit. This created `C:\Users\Me\AppData\Roaming\jupyter\kernels\python3\kernel.json`, and it points to the venv within which I ran the command:

```json
{
 "argv": [
  "C:\\Users\\Me\\.virtualenvs\\automation-xkIx0NF5\\Scripts\\python.exe",
  "-m",
  "ipykernel_launcher",
  "-f",
  "{connection_file}"
 ],
 "display_name": "Python 3",
 "language": "python"
}
```

Of course, within the venvs where I already use jupyter, they have kernel definitions for "python3" as well
`C:\Users\Me\.virtualenv\some-other-venv\share\jupyter\kernels\python3\kernel.json`


The kernel within the venv itself is apparently treated as a "system" kernel, which is why the kernel created through the suggested command which was put into AppData takes precedence over the those in the venvs. As a consequence, running jupyter within a venv will always use the python kernel from that one specific venv within which I happened to run the recommended commadn

![image](https://user-images.githubusercontent.com/349397/48259774-61261080-e419-11e8-8d1b-3b5dff02e5c9.png)

https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs

**Comment by willingc** [comment]
Hi folks,

We've recently improved our kernel documentation, and I hope it will clear up any confusion you may still have: https://nteract.io/kernels 

This page also links to the following Jupyter information on installing kernels: https://ipython.readthedocs.io/en/stable/install/kernel_install.html

There's additional information available here: https://docs.nteract.io/#/concepts/kernels

Hope this helps. :sunny:

**Comment by kiwi0fruit** [comment]
One of the points of this issue was to add a link to this page to the
nteract menu. When the app doesn't work it should be capable of resolving
the issue from within itself. Without the user remembering what page can
help and googling.

**Comment by kiwi0fruit** [comment]
I mean the link to the https://nteract.io/kernels page.

**Comment by willingc** [comment]
@kiwi0fruit,

The nteract help menu provides links out to resources. 

<img width="835" alt="screenshot 2018-12-17 19 28 48" src="https://user-images.githubusercontent.com/2680980/50130392-402fb700-0232-11e9-85a5-e0f8996a0044.png">

I've opened #3863. Pull requests are welcome.

**Comment by kiwi0fruit** [comment]
Great! I guess I didn't pay attention)

>
