### ISSUE TITLE
Nteract does not find or install Python 3 kernels

### ISSUE THREAD

**Issue by richlysakowski** [nteract/archived-desktop-app#3653]
There are no instructions or menu commands in Nteract to point it to the already installed Anaconda Python 3 runtime.  This is a design oversight.   We need to be able to easily configure it to use Python 3.   

Give us a menu command to navigate to and select the runtime we want to use.  

Or at least give us clear instructions on the Help menu.

Thank you.

**Comment by JNFoo** [comment]
I am experiencing the exact same issue. Installed the windows beta on a Win 10 system and had zero python functionality out of the box despite a complete newly updated Anaconda/Jupyter install. The software is not picking up the available ipython kernel(s) and there is no obvious way to direct it there.

**Comment by BenRussert** [comment]
@richdevboston Please remember this is a free and open source project that relies on the time and effort of regular people just like you. In fact, I've taken a few minutes of my Friday night to answer your questions for no other reason than the hope that you end up becoming a constructive member of our community!

My advice: Instead of making demands, try phrasing feedback as suggestions. This way your ideas and experiences can be extremely valuable.

Anyway, [check this link out](https://nteract.io/kernels/python) and let me know if it you still have the issue.
