### ISSUE TITLE
"Fix" ctrl + S to save the notebook, not the webpage

### ISSUE THREAD

**Issue by jackiekazil** [nteract/archived-desktop-app#3851]
**Is your feature request related to a problem? Please describe.**
I have muscle memory built in to hit ctrl + S to save my notebook. This action tries to save the web page to some location that I designate. Autosaves don't erase the fact that I still want to know the exact time it was saved, which would be the time that I hit ctrl + S (it not only saves, but it acts as a mental marker for "everything before this point is saved and everything after this point might not be"). 

**Describe the solution you'd like**
I would like ctrl + S to force a save of the notebook.

**Describe alternatives you've considered**
I live in a world of annoying pop ups that I have to move my mouse to clear. 🤷‍♀️ 

**Additional context**

**Comment by jackiekazil** [comment]
Related: #1584

**Comment by willingc** [comment]
Howdy @jackiekazil. FYI @captainsafia @rgbkrk. How big of a change would this be?

**Comment by rgbkrk** [comment]
We're going to be adding keyboard shortcuts in the coming weeks, this is definitely one of the first to go in. I assume this is for the web version of nteract since desktop does have this keybinding.

**Comment by jackiekazil** [comment]
Yes. This was in reference to the web version.

**Comment by captainsafia** [comment]
This still happens and is annoying. Reopening.

**Comment by BenRussert** [comment]
I tried to take a "quick" crack at this last night hoping it was just `event.preventDefault()` missing somewhere (that is part of it). 

The first problem I found is that `react-hotkeys` ignores `textinput` by default (the element focused in a cell normally). See [my wip branch here](https://github.com/nteract/nteract/compare/ben/fix-save-key-3851)

When I did get save to fire from the shortcut, I was running into issues with stale data (content references directory instead of active notebook file). I wondered if that was due to hot reloading or something, but stopped before looking into it too much.

**Comment by captainsafia** [comment]
Closing this since we are planning on deprecating the Jupyter extension in favor of the web app.
