### ISSUE TITLE
deprecate gatsby-transformer-ipynb

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#4060]
@captainsafia and  @rgbkrk I've seen that there is a lot of changes in the nteract since you're moving to typescript.I think it's time to move the gatsby-transformer-ipynb to another repo as his development is quite unrelated with nteract even if it uses notebook-render package .I already published it in @gatsby-contrib. Do you agree with that?

**Comment by rgbkrk** [comment]
Yeah I'm happy with that. We're trying to improve performance and change how `transforms` + `displayOrder` work.

**Comment by rgbkrk** [comment]
It's also cool to have it in another repo within nteract. Wherever you find it easy to lead it and bring in new contributors.

**Comment by captainsafia** [comment]
@benjaminabel I moved out the notebook-render project into [this repo](https://github.com/nteract/notebook-render) as part of the cleanup. It still needs some work before it can be released. Specifically, we'll want to summit some of the custom types we've created for things like `rehype-stringify` into DefinitelyTyped so that they can be used in the new package and by others.

**Comment by captainsafia** [comment]
Closed in https://github.com/nteract/nteract/pull/4080.
