### ISSUE TITLE
Data Explorer blueprintjs styles affect global styles

### ISSUE THREAD

**Issue by dylanross3** [nteract/archived-desktop-app#4261]
**Application or Package Used**
Data Explorer

**Describe the bug**
Following the instructions on the Data Explorer package [README](https://github.com/nteract/nteract/tree/master/packages/data-explorer), I am including the following imports in my application.

```
// Toolbars and other UI elements
import "@blueprintjs/core/lib/css/blueprint.css";
import "@blueprintjs/select/lib/css/blueprint-select.css";

// CSS for the grid view on the data explorer
import "react-table/react-table.css";
```

The blueprintjs styles are affecting the rest of my application.

**Expected behavior**
The imported styles should only affect the Data Explorer.

**Additional context**
Might be related to #3489.

As a side note, it's not a good practice to have the consumer import a transitive dependency of your package. Alternatives include importing the styles in the Data Explorer package itself or declaring it as a peer dependency.

**Comment by BenRussert** [comment]
I agree with your points completely and hope to find a good solution to this. If there is a better solution, I'd love to merge it.

I advocated for the current solution because the vendorizing we tried had a large performance impact and other difficult to diagnose problems. While this solution was annoying, it was simple and the one suggested by [blueprint](https://github.com/palantir/blueprint/).

As far as the title issue, I think that is a blueprint issue since [they indend to avoid this.](https://blueprintjs.com/docs/#core/classes.namespacing)

**Comment by oldpierrebrunelle** [comment]
Do we have any ETA of stance?

**Comment by emeeks** [comment]
@PierreBrunelle I plan to dig into a host of issues and features for Data Explorer next week. I plan to get it resolved either by figuring out a way to include the styles or by tearing out blueprint and replacing the controls with something that doesn't have this issue. So one way or the other it'll be fixed by next Friday.
