### ISSUE TITLE
Typo on the components page!

### ISSUE THREAD

**Issue by choldgraf** [nteract/archived-desktop-app#4262]
There's an accidental ass on your components page! :-)

https://components.nteract.io/#source

under "bring your own editor" there's a sentence that says "you can ass your own editor"! I tried finding where that page is served but I can't find it to make a PR, so I'm opening this issue instead!

**Comment by captainsafia** [comment]
Oh gosh! I should not have laughed when I saw this issue come up but I totally did. 

As it turns out, this was resolved in https://github.com/nteract/nteract/commit/380b2d0f75394470d6b33472ad7843cf11f467f0, but our docs page hasn't been redeployed since. I'm leave this open and redeploy the docs page tomorrow then close this issue.

**Comment by BenRussert** [comment]
Haha, here I was thinking I snuck the fix in before anyone noticed...

**Comment by captainsafia** [comment]
For more context into why the deploy was never done, we recently completed a TypeScript migration on the monorepo. As a result, our build configuration for styleguidist, our documentation rendering tool, is broken. As a result, doing a redeploy is not as simple as running `now docs:deploy` (which is usually the case), since the build configuration needs to be fixed.

**Comment by captainsafia** [comment]
And fixed! The build config was correct, it just wasn't picking up my project reference until I reran the package build. As it turns out, this is a result of the way `projectReferences` are implemented in `ts-loader`.

For future reference, if you run into issues with modules not being found, it is because `ts-loader` resolves but does not build references. So you have to rerun the build to get all the packages being referenced built.

**Comment by choldgraf** [comment]
ah ha - thanks for the extra context @captainsafia !

**Comment by rgbkrk** [comment]
Did #4251 fix the issues with the docs?

**Comment by captainsafia** [comment]
@rgbkrk: It did. I think it might’ve just been an issue with my build. Once I ran “yarn build” all the packages were loaded correctly. My last comment has more info.
