### ISSUE TITLE
nteract.components.io has windows style path separators 

### ISSUE THREAD

**Issue by BenRussert** [nteract/archived-desktop-app#4280]
See example below:
![windows-paths-rsg](https://user-images.githubusercontent.com/10860657/54499320-fd838680-48d5-11e9-8f88-daac61a28dcf.png)

Maybe I should open a react-styleguidist issue? I would think the build should be the same on all platforms by default.

**Comment by captainsafia** [comment]
This is probably because I was the last person to deploy the docs page and I did it on my Windows machine. We can use react-styleguidist [getComponentPathLine](https://github.com/styleguidist/react-styleguidist/blob/master/docs/Configuration.md#getcomponentpathline
) to override the default functionality and have it do something else. For example, we can replace it the path with an import statement. This makes sense since it already comes with a little copy icon for people to use.

**Comment by BenRussert** [comment]
Oh, cool. That's a good idea, the import statement seems more useful in this context.
