### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by davidanthoff** [nteract/archived-desktop-app#4309]
Would be great if there could be a new release of the desktop client! The last one was in November, there have been many things that have been fixed by now and I'd love to get a version that includes this.

Also, is there some place to get a sense of the roadmap/timeline/milestones for releases?

**Comment by captainsafia** [comment]
Very soon!

For background information, our release process is bottle-necked by the need for a App Store certificate. We can release for Windows and Linux pretty easily, but we've only got one license on one machine for the OS X release. As a result, our release process is slowed down.

If you or others are interested in helping the project get more licenses from Apple, you can [donate here](https://numfocus.salsalabs.org/donate-to-nteract/index.html).

**Comment by deeplook** [comment]
@captainsafia Is it no longer possible to build an macOS app bundle and let people download/install it from outside the app store? I can still see apps apparently built without a certificate which macOS will still install if you insist after complaining it's made by an "unregistered developer" or so.

**Comment by captainsafia** [comment]
@deeplook Yes, it is possible to build a bundle and distribute outside the App Store. The issue is around the Apple dev certificate. Although it might be possible to install without a certificate by changing security settings, we are trying to avoid doing this to ship a better experience for users.

We are working on shipping a release sometime this week. It's currently under QA and final prep.

**Comment by BenRussert** [comment]
Check out @nteractio’s Tweet: https://twitter.com/nteractio/status/1114196004809498624
