### ISSUE TITLE
nteract becomes unresponsive when backgrounded

### ISSUE THREAD

**Issue by jfhbrook** [nteract/archived-desktop-app#4531]
**Application or Package Used**

nteract desktop :)

**Describe the bug**
When nteract is spawned in a shell with `nteract &` it never shows a window; if it's backgrounded w/ `ctrl-z` then it becomes unresponsive until you run `fg` in the same terminal

**To Reproduce**

1. Crack open a terminal window
2. Run `nteract` in that terminal; nteract should spawn and be responsive
3. Press `ctrl-z` in the same terminal; nteract's window bar will gray out on osx and the app will become unresponsive
4. Type `fg RET` in the same terminal; nteract will be responsive again

**Expected behavior**
I'd like to be able to spawn an nteract in the background w/ `nteract &` in a terminal without issue. Practically speaking I don't use `ctrl-z`/`fg` much, it's just a simple way to reproduce the issue.

**Screenshots**
Not much to screenshot here beyond a gray bar in osx

**Desktop (please complete the following information):**

- OS:  currently reproducing on osx but have seen on my archbook as well
- Browser: the electron app
- Version: 0.14.5 apparently - I installed this from releases maybe a month ago? If there's a simple way for me to install something newer on osx I'm definitely game to give it a shot. I don't know the version I have in linux though aur suggests that it's [at 0.14.1 a stale package I need to get around to forking](https://aur.archlinux.org/packages/nteract-bin/)

**Additional context**
None that I know of. Just a minor nit I'd like to get sorted out!

**Comment by captainsafia** [comment]
Thanks for opening this issue, @jfhbrook!

Out of curiosity, why would you like to run the desktop app as a background process?

**Comment by jfhbrook** [comment]
I don't :) I want to be able to open notebooks from the cli without blocking the terminal, like how "open" works in OSX.

**Comment by captainsafia** [comment]
@jfhbrook Have you tried setting nteract as the default app for .ipynb files and using `open` that way?

**Comment by jfhbrook** [comment]
I haven't configured this in osx yet I don't think, but linux is actually the sticking point for me - I don't have a real desktop environment so xdg mime stuff is still a bit of a fiasco.

**Comment by jfhbrook** [comment]
anyway this isn't a blocker for me, now that I understand the problem I can work around, but it's *weird* and *probably not intended behavior* lol

**Comment by CrystallineCat** [comment]
nteract can't really do anything differently regarding the `Ctrl-Z` behaviour, because `Ctrl-Z` suspends a process (no more CPU time scheduled), rather than backgrounding it.

To background a suspended process, you have to use `bg` afterwards. See this for more detailed info: https://superuser.com/questions/476873/what-is-effect-of-ctrl-z-on-a-unix-linux-application

`nteract &` segfaulting, on the other hand, is definitely a problem.

**Comment by CrystallineCat** [comment]
Hmm... I looked more closely at what is happening with `nteract &`, and it seems that the process opens `/dev/tty` and then does operations with it, getting `SIGTTIN` 18 times since no tty is connected. Each `SIGTTIN` suspends the process. So by typing in `bg` 18 times to resume after each signal you can get it to actually run in the background.

This whole thing appears to happen really early in the process, before we even hit our first log call, I'm pretty sure it's in code that's not nteract, but electron or nodejs. I have no idea how to change this behaviour.

**Comment by willingc** [comment]
Thanks for the detailed research @CrystallineCat. I'm going to go ahead and close this at this time. If folks wish to file an enhancement issue, please do so. Thanks.
