### ISSUE TITLE
Option for disabling autosave

### ISSUE THREAD

**Issue by PaulSoderlind** [nteract/archived-desktop-app#4567]
I often want to just view my notebook. Other times I want to work on the code before saving. In these cases, the current autosave  is a nuisance. I would suggest having an option for disabling autosave - or (alternatively) autosave to a temporary file.

**Comment by languy** [comment]
+1
The auto-save was not designed with multiple notebooks opened in the same app scenario. There is a single timer that will trigger auto-save for all the notebooks at the same time. One we close a notebook, the timer still runs and saves (but there is logic to skip saving if there's no content for the notebook).

It would be great if we can move that auto-save logic into the notebook-app-component so that we can turn it on/off per notebook when appropriate wrt to its lifecycle.

**Comment by andrewfogg** [comment]
I would like to add my voice to this.  I do a lot of exploratory work using data explorer and it appears that the autosaving is constantly increasing the size of the notebook on the hard disk and degrading performance of nteract (typing hangs / is slow).

**Comment by AndyTheFactory** [comment]
What I noticed is that since the autosave feature the notebooks lag more often without even with the kernel freshly loaded.

**Comment by captainsafia** [comment]
Howdy folks! Thanks for posting this feedback. Some thoughts.

- Considering the number of issues we were getting before hand about people encountering data loss because they thought that nteract had the same auto-save experience as Jupyter, I don't think we'll go through with disabling it by default on the desktop and web apps.
- Consumers of the nteract SDK can "disable" auto-save by de-registering the auto save epic from the epic middleware in their applications.

With regard to the perf and customizability of the auto-save interval. It's currently sent to auto-save around every 30 seconds which is a little bit greedy. We can probably up this to the 1 to 2 minute range by default.

Also, we'll want to refactor the way the autosave interval is stored. Currently, it's a local variable. If it's configured to read from state, people can customize it as they see fit and optionally disable it (have to figure out if this is possible by passing 0 as the interval time or something).

Some next steps for this:
1. Refactor the interval sample range for the auto-save epic from a set of hardcoded values to ones that are dynamically generated given a set interval
2. Support storing an optional auto-save interval option in the config for the nteract desktop app
3. Hook up config in #2 to interval generation function in #1

**Comment by captainsafia** [comment]
Update: the auto-save interval is no configurable via the `nteract.json` config file. You can set it to 0 to disable auto-save altogether.

This will be shipped in the next release of the nteract desktop app which will likely happen after the new year.
