### ISSUE TITLE
Confused when executing and kernel not connected.

### ISSUE THREAD

**Issue by Carreau** [nteract/archived-desktop-app#457]
It should at least clear the input prompt number.

(maybe pop a red notification on the upper right, like the gist uploaded one.)

Something else felt weird when this happened,  but it's hard to tell what.

**Comment by jdfreder** [comment]
I think in the jupyter/notebook if the kernel is not connected the "executing" execution state of the cell is set, is that right?  Should we use that behavior here instead of clearing the prompt number?  

Personal opinion, I think clearing the prompt number makes more sense, because the "executing" state implies that when the kernel is connected, the cells will be executed.
