### ISSUE TITLE
Jupyter Server endpoint associated with kernel

### ISSUE THREAD

**Issue by lbarons** [nteract/archived-desktop-app#4627]
We have a scenario where we need to be able to easily map the jupyter server endpoint of the host to the associated kernel. 
Scenario: pick which contentRef by the related kernelRef that had the endpoint of the selected host.

Right now there is no mapping maintained in the kernelRef, and a non-consistent workaround (within channels->_source).

Example of a state that would solve this scenario for us:
![image](https://user-images.githubusercontent.com/9374083/67228147-912db000-f3ed-11e9-9c5c-12d68071a944.png)

**Comment by captainsafia** [comment]
So, it turns out that the `RemoteKernelRecord` type definition already contains a reference to the `hostRef` as seen above. However, this is not being set in the `launchWebSocketKernelEpic` once the kernel has been successfully launched.

So, to solve this problem, what will need to be changed is.

1. Set the hostRef in the RemoteKernelRecord within the `launchWebSocketKernelEpic`.
2. Provide a selector for retrieving the hostRecord for a given hostRef.

With this option, API consumers can extract the hostRef from the RemoteKernelRecord once it has been set correctly in #1, retrieve the HostRecord using #2, then extract the endpoint from that.

**Comment by captainsafia** [comment]
@lbarons This is now released in the latest version of @nteract/core.
