### ISSUE TITLE
A way to import CM syntax highlighter theme

### ISSUE THREAD

**Issue by ivanradicek** [nteract/archived-desktop-app#4631]
**Is your feature request related to a problem? Please describe.**

I'd like to have syntax highlighting style to match the CodeMirror theme used in the notebook cells. I'm using `react-syntax-highlighter` and would like to use the theme provided in the file: https://github.com/nteract/nteract/blob/master/packages/presentational-components/src/syntax-highlighter/theme.ts However, this file is not exported, and hence I cannot import it from my code.

**Describe the solution you'd like**

It would be great if the mentioned theme file is exported in the `presentational-components` package.

**Describe alternatives you've considered**

1. Using `Source` component directly - however, this component has its own styling that does not match CodeMirror styling.
2. Copying the mentioned file to own source tree - however, this works as a temporary fix, and will stop working once the CodeMirror styling changes.

**Additional context**

N/A

**Comment by captainsafia** [comment]
Hello @ivanradicek! Sorry this request slipped by the way-side. I'll go ahead and update the code so the style is exported today.

**Comment by captainsafia** [comment]
My bad! I realized that after a recent upgrade to a new major version of react-syntax-highlighter, we are actually no longer using this copied theme file. Instead, you can use the the themes from the `react-syntax-highlighter` directly for your use case. The themes are exported under `react-syntax-highlighter/dist/cjs/styles/prism/`.

I'll go ahead and close this issue now. Glad we are moving to using themes that are exported in other packages instead of our own forks. Better for maintainability...
