### ISSUE TITLE
Box-based ipywidgets do not render

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4640]
**Application or Package Used**
@nteract/jupyter-widgets

**Describe the bug**
The current implementation of the jupyter-widgets package does not render Box-based widgets like Box, VBox, and HBox.

**To Reproduce**

1. Create a new notebook.
2. Attempt to create a box widget. Note that no widget is not rendered.

```
import ipywidgets
items = [ipywidgets.Label(str(i)) for i in range(4)]
ipywidgets.Box(items)
```

**Expected behavior**
Layout-based widgets should render.

**Desktop (please complete the following information):**
master

**Comment by miduncan** [comment]
Found the issue here. It ended up being separate from the issues of the Accordion, Tabs, and interact().

What caused this issue was that we were manually attaching the element to the view. At first we were doing this by passing it to the view constructor, and then we switched to setting `view.el = el`. Box based widgets are written in a weird way so that their element cannot be set without throwing an exception. They create a Phosphor element upon creation, and to render that to an element you _have_ to attach it using a special Phosphor attach method (annoyingly, this isn't documented).
