### ISSUE TITLE
Implement _get_comm_info function to rehydrate comms

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#4675]
We need to implement a `_get_comm_info` method that requests info about the active comms from the kernel so that we can rehydrate the state when we refresh the page without changing the kernel.

cc: @miduncan

**Comment by miduncan** [comment]
I looked into this today, and here is my current understanding of how this `_get_comm_info` flow works and why I don't think it is right for our scenario:

1. `_get_comm_info` sends a [message](https://jupyter-client.readthedocs.io/en/latest/messaging.html#comm-info) to the kernel, specifying the 'jupyter.widgets' target
2. Kernel responds by sending a list of `comm_id`s (which map to `model_id`s)
3. `Manager` creates a `Comm` for each `comm_id` and sends a `request_state` message to get the data it needs

In our flow, since we are already given a `model_id` before we even instantiate `Manager`, I think we should modify our code to get the model information to be something like this:
```
try{
  return getModelById(id)
}catch{
  return await requestState(id)
}finally{
  throw ...
}
```
