### ISSUE TITLE
Use nteract on the browser without the jupyter server?

### ISSUE THREAD

**Issue by aviks** [nteract/archived-desktop-app#4685]
So I think the nteract-desktop talks directly to the kernel, it does not need the jupyter-notebook webserver to be running. Is it possible to run the nteract on the browser in the same way, directly to the kernel, without the jupyter-notebook webserver in the middle? I couldn't figure this out from the docs. 

(Apologies if this is not the right forum to ask questions -- feel to close this)

**Comment by BenRussert** [comment]
There would need to be a server somewhere in order to run a kernel and talk to it from a browser since you can't run a kernel executable from the web browser (client).

It would be possible to write your own server, but I think it would be a lot easier and more secure to go with either electron (like the desktop app) or a server using existing jupyter server apis (like the nteract notebook extension does).

Does that answer your question?

**Comment by captainsafia** [comment]
Ditto what @BenRussert said!

The nteract web app is built as a Jupyter extension -- which requires a Jupyter server to be running. You could build a nteract client that is not packaged as a Jupyter extension but you'd still have to communicate with the kernel over WebSockets as opposed to the 0mq-based communication that is used by the kernel.

I'll go ahead and close this issue since there isn't any action to take on it.
