### ISSUE TITLE
Upgrading plotly.js to v1.51.2

### ISSUE THREAD

**Issue by nicolaskruchten** [nteract/archived-desktop-app#4722]
**Is your feature request related to a problem? Please describe.**

Executing Plotly.py code (in the desktop app) such as that documented in https://plot.ly/python/imshow/ doesn't work, because the on-board version of plotly.js is inferior to 1.51

**Describe the solution you'd like**

Plotly.js should be upgraded to version 1.51.2

I'm happy to provide a PR for this when we bump plotly.js ... should i just bump the version dependency here https://github.com/nteract/nteract/blob/master/packages/transform-plotly/package.json#L16 ?

**Comment by captainsafia** [comment]
Hello @nicolaskruchten!

Yes, bumping that package number would be great. When you do so, make sure that you run a `yarn install` to update the `yarn.lock` file as well.

Also, we should look into why our automated updated bot didn't pick up this new release. That would make things easier in the future since we'd get bot PRs for each new release of the plotly.js-dist package.

**Comment by nicolaskruchten** [comment]
Ok cool! And then you’d release a patch version of transform-Plotly each time? Like 6.0.1 kind of thing?

**Comment by nicolaskruchten** [comment]
PS: yes, using a bot here would be fantastic! :)

**Comment by captainsafia** [comment]
I'm going to go ahead and close this now since it was resolved in #4773.
