### ISSUE TITLE
Components documentation import line is misleading

### ISSUE THREAD

**Issue by Keno** [nteract/archived-desktop-app#4791]
In the [nteract components documentation](https://components.nteract.io/#!/Plaintext) for e.g. the `Plain` component, the first line suggests that the component can be used as

```
import { Plain } from '@nteract/outputs';
```

However, this doesn't seem to actually work. Instead, the component needs to be used as `Media.Plain` (and is referenced as such elsewhere). It would be nice to either make the suggested import work or adjust the snippet to the correct usage.

**Comment by captainsafia** [comment]
Thanks for reporting this issue, @keno.

Currently, the imports are generated auto-magically by our documentation generator. The documentation generator generates the import snippet under the assumption that the import follows the usual schema.

To solve this problem, we either need to:
- Hide the auto-generated import in the docs and add the imports ourselves
- Update our code to export the components that are currently under “Media” to be top-level exports.

I’m leaning towards the first solution since those auto-generated import statements have gotten us in trouble before.

Would you be interested in submitting a pull request for this?

**Comment by wadethestealth** [comment]
I also lean towards the first option as this seems the most logical in terms of the package structure, and we use import { Media } inside Hydrogen.

**Comment by Keno** [comment]
I do think having a ready copy-able snippet is useful, esp. since the code examples, use `require`, which doesn't seem like the recommended way to import these components.

> Would you be interested in submitting a pull request for this?

I'm unlikely to get around to this.

**Comment by wadethestealth** [comment]
@keno an import is a require. You may use either or.
