### ISSUE TITLE
Optional install location

### ISSUE THREAD

**Issue by tomrod-pcci** [nteract/archived-desktop-app#4804]
**Is your feature request related to a problem? Please describe.**
When attempting to install, it defaults to Program Files. Better would be to let the user define where to install, in case they want to install in user-space only. Users without admin access cannot install to C:/Program Files/*

**Describe the solution you'd like**
Please provide an option at install to allow for users to decide where to install their programs.

**Comment by captainsafia** [comment]
Hello @tomrod-pcci -- thanks for opening this issue.

In order to enable this, we'll need to enable `allowToChangeInstallationDirectory` in our electron-builder configuration. This is documented further in [this docs page](https://www.electron.build/configuration/nsis).

I'll leave this open in case someone wants to take a look at tackling it.
