### ISSUE TITLE
A text box and submit button appear in the output after executing a cell

### ISSUE THREAD

**Issue by victor-meng** [nteract/archived-desktop-app#4856]
**Application or Package Used**
nteract on jupyter

**Describe the bug**
After executing any cell, a text box and submit button apear inside the output of that cell.

**To Reproduce**

1. Make sure the package versions are the same as the versions listed in the attached package-lock.json file: [package-lock.zip](https://github.com/nteract/nteract/files/4106476/package-lock.zip)

2. Open any notebook or create a new notebook.
3. Execute any cell in the notebook
4. Observe that the text box and submit button shows up in the output

**Expected behavior**
The text box and submit button should not appear if we don't dispatch any promptInputRequest events.

**Screenshots**
![image](https://user-images.githubusercontent.com/56978073/73037405-ca6a2780-3e03-11ea-99b5-1984fbf7f206.png)

**Desktop (please complete the following information):**

- OS: [e.g. macOS]

**Additional context**
In the Redux devtools, no `PROMPT_INPUT_REQUEST` action was dispatched. The only action that modified the cellPrompts property in the state was `SEND_EXECUTE_REQUEST`:
![image](https://user-images.githubusercontent.com/56978073/73037995-b58e9380-3e05-11ea-9211-807237c67e3f.png)

**Comment by captainsafia** [comment]
Thanks for opening this issue, @victor-meng! This one is a rather interesting one.

After some digging around, I suspect that this problem is occurring as a result of a version mismatch between the `@nteract/types` an `@nteract/reducers` package. Here's what I am suspecting is happening.

Recently, the type on `cellPrompts` was updated from being a single value to multiple values. This was done to support scenarios where the kernel would return multiple `stdin` responses to the same execution request.

This is why the type that is set in `cellPrompts` is a list and not an empty object. The `SendExecuteRequest` action sends a change that updates the transient `status` property of a cell. I suspect that Redux sets the undefined `cellPrompts` under the transient state to an empty list.

The fact that `cellPrompts` is set to an empty list is fine, assuming that the UI is set to handle this case.

When the update mentioned above (to make `cellPrompts` a list instead of a single value) was made, the nteract UI was updated to handle empty lists and not render anything.

I suspect what is happening is that your UI is still expecting `cellPrompts` to be a single value and is interpreting the empty list as a non-null object.

To resolve this, I would recommend:

- Updating the cell prompt display logic in your notebook app

Also, you might want to consider taking a look at the new `stateful-components` model for building UIs. Some examples of notebook apps you can build are provided [here](https://github.com/nteract/nteract/tree/master/packages/notebook-app-component/src/notebook-apps).

Let me know if you have any follow-up questions/clarifications.

**Comment by victor-meng** [comment]
Thanks for looking into this Safia! I believe you are correct. Our package-lock.json was updated inadvertently which caused some nteract packages to be upgraded but not all. It's very possible that there were some version mismatches between different nteract packages.

I'm going to upgrade the nteract packages properly and update the cell prompt logics this week. I will let you know if I run into this issue again.
