### ISSUE TITLE
Missing Syntax for the Elm Language

### ISSUE THREAD

**Issue by eimfach** [nteract/archived-desktop-app#4884]
**Application or Package Used**
nteract desktop macOS Catalina

**Describe the bug**
Missing Syntax Highlighting with the elm-kernel also referenced at the elm-kernel repo:
https://github.com/abingham/jupyter-elm-kernel/issues/24

**To Reproduce**
1. Install Elm Kernel https://github.com/abingham/jupyter-elm-kernel
2. Write a block of elm code like :

```
import Html
import Regex

isAddressingSilent remark =
    case Regex.fromString "^\\s*$" of
        Just whiteSpaceRegex ->
            Regex.contains whiteSpaceRegex remark

        Nothing ->
            False
            
main =
    let
        adressSilent =
            isAddressingSilent "\n\u{000D} \t"
    in
    if adressSilent then
        Html.text "Fine. Be that way !"
    else
        Html.text "Whatever."
-- compile-code
```

**Expected behavior**
Syntax Highlighting does work.

**Screenshots**
<img width="799" alt="Bildschirmfoto 2020-01-28 um 20 38 34" src="https://user-images.githubusercontent.com/6602910/73299086-ce84b380-420e-11ea-8c71-91db0bf6ceea.png">

**Desktop (please complete the following information):**
macOS 10.15.2

**Comment by captainsafia** [comment]
Hello again, @eimfach!

I suspect that this is because we don't load the Codemirror Elm-mode in the CodeMirror editor.

CodeMirror exposes syntax highlighting for each language via modes, which are auxillary JavaScript modules loaded into the CodeMirror editor.

If you are interested in making a contribution to add support for Elm natively in nteract, you can do so by adding [the Elm CodeMirror mode](https://codemirror.net/mode/elm/) to the list of registered modes in the CodeMirror editor ([link](https://github.com/nteract/nteract/blob/bb2842b29a268ef1c8042ab669765573d3612c73/packages/editor/src/index.tsx#L199).

I'll tag this as new-contributor-friendly for anyone who is interested in tackling this.

**Comment by eimfach** [comment]
Hey @captainsafia, alright will have a look at this, thanks !

**Comment by captainsafia** [comment]
Closing this now. It will be included in next month's release. Thanks for the contribution!
