### ISSUE TITLE
021.0 Desktop, autoSaveInterval

### ISSUE THREAD

**Issue by PaulSoderlind** [nteract/archived-desktop-app#4888]
setting 
`{
  "autoSaveInterval": 0,
}`

does not stop nteract 0.21.0 from autosaving on Win 10 64 (tested on several machines)

**Comment by captainsafia** [comment]
Oh no, @PaulSoderlind! This feature was made just for you in mind. :) 

I'll take some time today or tomorrow to debug the loadConfigEpic and see why this might be happening.

Quick question: what is the location of your nteract.json config?

**Comment by PaulSoderlind** [comment]
Thanks, that's very kind of you.

My nteract.json is at `C:\Users\XXX\.jupyter\nteract.json`

**Comment by captainsafia** [comment]
Hello @PaulSoderlind! As you see, this issue was closed.

Turns out, there was a bug in the config loading logic for the desktop app. It returned a value different from what other config load logic in the codebase expects. This is fixed now and will go in the next release.

Thanks for your patience as we sort out these issues and sharpen the experience here.
