### ISSUE TITLE
CHANGELOG missing

### ISSUE THREAD

**Issue by MichaelDeBoey** [nteract/archived-desktop-app#4924]
I just saw that `ansi-to-react` is updated to `v6.0.0`, but I can't find any CHANGELOG to check out the changes.

Would you guys be so kind to provide us with a decent CHANGELOG please? 🙂

Thanks for all your hard work! 🙂

**Comment by captainsafia** [comment]
Hello Michael! Apologies for the trouble you had tracking the changelog. We keep our changelogs [here](https://github.com/nteract/nteract/tree/master/changelogs). The changelog details aren't categorized per-package yet so it is harder to parse what changes are associated with which package, especially since we maintain so many packages.

In the future, the changelog will be organized per package and you can use it to find changes.

In the meantime, the key changes that went into the 6.0.0 release are linked here:

* Adding support for ansi-decoration classes (https://github.com/nteract/nteract/pull/4875)
* A bug fix for how background and foreground colors are set (https://github.com/nteract/nteract/commit/8c87e1875fb1efc7547789e01bd781f545eb6afe#diff-b116b6808aa78692fc40ca447f341b16)

I hope this is helpful!
