### ISSUE TITLE
Toggle "Execute failed" for markdown cells.

### ISSUE THREAD

**Issue by thomascamminady** [nteract/archived-desktop-app#4961]
A common situation is to have code cells mixed with markdown cells. 
I tend to `shift+enter` through cells when opening a new notebook and find it rather irritating to get an error message when `shift+enter`ing through a markdown cell, see the image below.

![Screenshot_20200227_092530](https://user-images.githubusercontent.com/24543638/75425610-5d3a3c80-5943-11ea-9f09-ab4a48d3a8ff.png)

This does not happen when using e.g. `jupyter lab`. I see that this is a desired feature as it is implemented in `packages/epics/src/execute/execute.ts`:
![Screenshot_20200227_093146](https://user-images.githubusercontent.com/24543638/75426014-100a9a80-5944-11ea-8ef9-c2e4ff96f6f0.png)

But maybe there would be the chance to toggle this error message off? Or display a warning instead?

**Comment by willingc** [comment]
Thanks @camminady for reporting this issue.

Confirming that I see the same behavior when running the example Python notebooks on 0.22. There is also a typo in the error box.

**Comment by jarmokivekas** [comment]
The way I see it, if a markdown cell makes it all the way to the cell type check in https://github.com/nteract/nteract/blob/c21cb9dd43c9f25165ead0167ec5643e52f62c57/packages/epics/src/execute/execute.ts#L359
it's ok to throw an error, since endering markdown is isn't the kernel's task (that check is already more of a backend functionality). The fix should probably be more toward the frontend, i.e ctlr-enter or shift-enter on a markdown cell shouldn't send a request or execution in the first place, right?

**Comment by jarmokivekas** [comment]
Closing this as fixed in #5061
