### ISSUE TITLE
Error opening app - cannot find module 'commander'

### ISSUE THREAD

**Issue by robintw** [nteract/archived-desktop-app#499]
When running `npm run start`, I get the following error in a GUI message box:

```
The app provided is not a valid Electron app, please read the docs on how to write one...

Error: cannot find module 'commander'
```

Any ideas?

**Comment by rgbkrk** [comment]
What happened during the `npm install`?

I'm guessing that it failed, likely choking on `zmq` and then didn't leave some dependencies behind. Since commander is one of the first that are loaded, that's the first to error. Open to digging further.

What OS are you on?
What's the output of `node --version`?

**Comment by robintw** [comment]
I'm on OS X, and have just upgraded node to version 6, deleted `node_modules` and started again and it all works ok now. I think you were right about missing dependencies because of an npm install issue.

Thanks!
