### ISSUE TITLE
Include golang syntax highlighting support in Codemirror

### ISSUE THREAD

**Issue by vsivsi** [nteract/archived-desktop-app#5055]
**Is your feature request related to a problem? Please describe.**
Using Nteract with the [Gophernotes](https://github.com/gopherdata/gophernotes) kernel generally works great! Except there's no syntax highlighting! It works fine in JupyterLab and classic Jupyter notebooks.

First reported here: https://github.com/gopherdata/gophernotes/issues/158

**Describe the solution you'd like**
Enable support for golang in CodeMirror.  Possibly here(?): 

https://github.com/nteract/nteract/blob/master/packages/editor/src/index.tsx#L211

**Describe alternatives you've considered**
I guess I could just use JupyterLab...

**Additional context**

Jupyterlab:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/428642/79600312-d03a7680-809b-11ea-9024-a6c95ee2e146.png">

Nteract:

<img width="508" alt="image" src="https://user-images.githubusercontent.com/428642/79600362-e47e7380-809b-11ea-8450-f0c54bc1fb69.png">

**Comment by captainsafia** [comment]
The good news is that syntax coloring is relatively easy to add in nteract. It's controlled by CodeMirror and we can add support for Go by adding the Go codemirror mode [here](https://github.com/nteract/nteract/blob/master/packages/editor/src/index.tsx#L222).

```
require("codemirror/mode/go/go");
```

Would you be interested in submitting a PR with this change?

Interestingly enough, I'm surprised that Go syntax highlighting works in JupyterLab because it doesn't look like that CodeMirror mode is included [there](https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/packages/codemirror/src/mode.ts) so perhaps there is a way to automatically download codemirror modes when a notebook from a particular type is loaded.

**Comment by daxian-dbw** [comment]
@captainsafia I was about to add entries for syntax coloring for c#, but found that `codemirror/mode/clike/clike` is already there, which should cover c# (https://codemirror.net/mode/clike/). Why is c# still not properly syntax colored on macOS?

<img src="https://user-images.githubusercontent.com/127450/80034274-ff3d5780-84a2-11ea-8931-96b8ab81e87b.png" width="300" height="200">

**Comment by Gozala** [comment]
> nterestingly enough, I'm surprised that Go syntax highlighting works in JupyterLab because it doesn't look like that CodeMirror mode is included [there](https://github.com/jupyterlab/jupyterlab/blob/f0153e0258b32674c9aec106383ddf7b618cebab/packages/codemirror/src/mode.ts) so perhaps there is a way to automatically download codemirror modes when a notebook from a particular type is loaded.

There is in fact a way to do that see
https://codemirror.net/demo/loadmode.html
however it depends on script injection and assumes Codemirror global (see corresponding plugin)
https://github.com/codemirror/CodeMirror/blob/master/addon/mode/loadmode.js
