### ISSUE TITLE
what a mess

### ISSUE THREAD

**Issue by lewisl** [nteract/archived-desktop-app#5068]
**Application or Package Used**
nteract desktop

**Describe the bug**
1. Save and lose everything:  replaces the notebook with one of size 0.
2. Once you click to edit a markdown cell in edit mode, you can never close the edit view.

**To Reproduce**
Just use it on Macos.

If I thought Jupyter and Jupyterlab were clunky, at least they work. You've made something pretty clunky much clunkier.

I realize this is not very constructive, but I think you need to realize.  Hydrogen in Atom is much the same.

You are clearly capable of good work so why not just pitch in to the Jupyter work instead of trying to create a commercial (some day, I realize not yet...) fork.

**Comment by captainsafia** [comment]
While we understand your frustration, this issue is non-productive and malicious. nteract is an open-source community supported by volunteer efforts and a small collection of corporate sponsors. We do what we can when possible.

No software is perfect and our community members work hard to improve the ecosystem everyday, sans compensation and often in the face of comments like this. We are part of the Jupyter ecosystem and collaborate actively with other projects throughout the community.

Note: this issue is in violation of [our community Code of Conduct](https://github.com/nteract/nteract/blob/e31a3a092e2b586063b1d4e27d9635fbbf99cd8f/CODE_OF_CONDUCT.md) and has been reported to GitHub.
