### ISSUE TITLE
Outputs cannot be collapsed after expanded

### ISSUE THREAD

**Issue by bryanchen-d** [nteract/archived-desktop-app#5071]
**Application or Package Used**
@nteract/core

**Describe the bug**
The outputs panel of a cell without initial metadata value of "collapsed" and "outputExpanded" cannot be collapsed after expanded

**To Reproduce**

1. Load notebook
2. Expand output on a cell which has no metadata of the expansion values
3. Try to toggle the expansion

And it cannot be toggled back

**Expected behavior**
Outputs can be collapsed

**Comment by bryanchen-d** [comment]
I believe this is something to do with the change https://github.com/nteract/nteract/pull/4972.
Where for a cell with no metadata values, when toggleExpansion happens, we set both `collapsed` and `outputExpanded` to true or false at the same time. Then the condition check below (collapsed===false || outputExpanded) will always return true.

I think in setting the metadata, would better to evaluate the expansion status first and then set it into the metadatas.

**Comment by captainsafia** [comment]
Thanks for opening this issue and doing some preliminary investigation, @bryanchen-d.

*groan* because this issue really highlights the need for resolving #4448 since we would've probably caught this in a release.

That aside, the ideally fix is to remove the `outputExpanded` property all together. Since the `collapsed` field is part of the official nbformat, we no longer need to work on our existing workaround.

This change should be as straight forward as searching for `outputExpanded` throughout the codebase and removing the references.

This will be a bit of a breaking change on the commutable side of things since it removes an existing field but it shouldn't be too catastrophic since there is a collapsed property in the standard,

**Comment by captainsafia** [comment]
Adding this to the May milestone and reffing it to #4448. We can probably resolve both issues in the same PR by adding the UI for collapse support and removing the duplicative `outputExpanded` property.

**Comment by captainsafia** [comment]
So, I looked into this. The expanded property is being toggled correctly. If you go to the cell toolbar and select "Toggle Expanded Output", you'll notice that the "expanded" class set in the Output component is toggled correctly.

However, we were missing the styles that were associated with the expanded class so I've fixed that in #5085.

Closing this now as no repro.
