### ISSUE TITLE
Add support for automagically loading required CodeMirror mode for languages

### ISSUE THREAD

**Issue by Gozala** [nteract/archived-desktop-app#5072]
**Is your feature request related to a problem? Please describe.**

I have being using jupyter-notebook with in combination with [rust kernel](https://github.com/google/evcxr/tree/master/evcxr_jupyter) and after discovering nteract I tried to use it there.

Good news is it worked out of the box and I did not had to do anything to make it work.

Bad news is (unlike junyper-notebook) code blocks don't seem to be syntax highlighted.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Continue using junyper-notebook

**Additional context**
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/21236/80157818-dd63d380-857b-11ea-9028-4afa93dd50bb.png">
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/21236/80157842-e785d200-857b-11ea-8060-59fe1360db37.png">

**Comment by captainsafia** [comment]
Glad the getting started experience with Rust worked well, @Gozala!

The hiccup you mentioned is a popular one these days. I provided an explanation as to why syntax highlighting is lacking for some languages [here](https://github.com/nteract/nteract/issues/5055#issuecomment-615554313).

Would you be interested in adding support for rust highlighting per the directions outlined in the link above?

This will have to do until we can figure out how to dynamically load syntax highlighting.

**Comment by captainsafia** [comment]
Re-purposing this issue to be more generic.

As mentioned [here](https://github.com/nteract/nteract/issues/5055#issuecomment-619239182), there is a loadmode extension that will automatically determine the codemirror mode to require. We should consider migrating this to our CodeMirror implementation to reduce the number of requires that are built in.

**Comment by bolariin** [comment]
I would like to give this a try if no one is working on it

**Comment by captainsafia** [comment]
Sure! I've assigned this to you.

**Comment by bolariin** [comment]
I ran into a block while working on this issue and wondering if I could get help on this. From looking at https://github.com/codemirror/CodeMirror/blob/master/addon/mode/loadmode.js, it looks like the trick here is to be able to load the Codemirror mode on demand. My attempts so far to do this have resulted in ` Critical dependency: the request of a dependency is an expression`

Looking through [codemirror/addon/loadmore.js](https://github.com/codemirror/CodeMirror/blob/master/addon/mode/loadmode.js)
that was mentioned in the linked issue. It looks like codemirror loadmode is changing the file for the script tag. 

I also took a look at jupyterlab since it was mentioned in the linked issue and it looks like they have a way to fetch the mode asynchronously
https://github.com/jupyterlab/jupyterlab/blob/71f07379b184d5b0b8b67b55163d27194a61a0ac/packages/codemirror/src/mode.ts#L71-L83. I also came across [this](https://gist.github.com/rigwild/ce6b4c6a893c3a95f75cc0aca633f037) but ran into the same error while trying to recreate it

The current issue I'm running into trying to recreate a way of loading the mode asynchronously
