### ISSUE TITLE
"The application “nteract” can’t be opened." in macOS

### ISSUE THREAD

**Issue by vaskatta** [nteract/archived-desktop-app#5111]
**Application or Package Used**
nteract desktop

**Describe the bug**
After installation I can't open the app in macOS. I get the message "The application “nteract” can’t be opened." Right clicking and clicking "open" gives the same result as double clicking on the icon. 

**To Reproduce**

1. Go to "Applications"
2. Double click on “nteract”

Also when
2. Right  click on “nteract”

3. See error 

**Expected behavior**
The application opens, if not on double click then when I right click and authorise it. 

**Screenshots**
<img width="419" alt="image" src="https://user-images.githubusercontent.com/30442505/82098025-0818f600-96fc-11ea-8c03-ca5b51f4b9af.png">

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.4 (19E287)
- Browse:r I have both Safari and Chrome
- Version: nteract-0.23.1-mac

**Additional context**

**Comment by captainsafia** [comment]
After attempting to open nteract, do you see any messages under System Preferences > Privacy and Security?

The nteract desktop app is certified as a macOS application but Apple recently introduced some new certification requirements that we have to work through. There is a chance that the nteract app was flagged by Apple's app security checks because of this.

**Comment by vaskatta** [comment]
Hi Safia,

I don't see any messages there but I may be looking at the wrong place.
Under Security and Privacy I have 4 tabs (General, FileVault, Firewall,
Privacy) but none of them seem to contain any messages about nteract.

Many Thanks,

Vaska

**Comment by captainsafia** [comment]
Interesting -- so this appears unrelated to the integrity issue mentioned above.

Does clicking the "?" in the dialog box provide a reference to more helpful logs or details?

**Comment by vaskatta** [comment]
No, unfortunately, only a blank page opens.

**Comment by captainsafia** [comment]
@vaskatta I see. Unfortunately, I've never seen this issue before. I'd recommend doing a clean uninstall of the nteract app, using something like [AppCleaner](https://freemacsoft.net/appcleaner/) to ensure that any orphan files are removed as well. After that, trying re-installing again and se if that resolves the issue.

**Comment by onebacha** [comment]
I had the same problem and this solution worked for me. I uninstalled nteract with CleanMyMac and then re-downloaded + re-installed it. nteract was able to open then.

**Comment by sasikiran** [comment]
If a macOS user downloads the zip file release and unzips it with the default 'Archive Utility' app, the app doesn't work and we are greeted with the 'The app 'nteract' can't be opened' message with nothing shown in the Security Preferences. Safari automatically opens zip files using the mentioned app by default.

If the user opens the zip file with another program such as 'The unarchiver', nteract works. [Example screenshot here.](https://imgur.com/mvwLoxp)
Also, if the user installs the app via the dmg file, it works.

**Comment by captainsafia** [comment]
Thanks for sharing these additional details, @sasikiran!

I'm closing this thread now since I don't think there's anything we can do within our app packaging to resolve this. We've recently configured our mac app for notarization so that might help resolve things.

In the event that others run into these issue, I hope the workarounds documented here will be helpful. If not, please open a new issue.
