### ISSUE TITLE
Does not save the theme

### ISSUE THREAD

**Issue by CapBlood** [nteract/archived-desktop-app#5134]
**Application**
nteract desktop

**Describe the bug**
nteract does not save the theme

**To Reproduce**

1. Preferences -> Theme -> Dark
2. Restart app

**Expected behavior**
I was expecting a dark theme:(

**Desktop:**

- OS: macOS and Ubuntu
- Version: 0.23.3

**Additional context**
- This problem also exists in version 0.23.2, but not in 0.23.1. 
- nteract saves theme settings to the nteract.json file, but ignores the theme parameter at startup

**Comment by captainsafia** [comment]
Thanks for reporting this issue!

We recently refactored our config handling logic and it appears a bug was introduced in the refactor.

It appears that settings and savings settings for a single file is working well but there is an issue with merging the contents of the `nteract.json`with the runtime config.

I missed this in my review of the PR because I didn't restart the nteract app to validate that the changes went through.

@CrystallineCat Any idea what might be fishy here?

**Comment by CrystallineCat** [comment]
The action that loads the config in the `notebook`-thread isn't being dispatched. I think I accidentally removed part of that mechanism one or two patches too early. In any case, this will be fixed by #5137. If you want me to make a quick fix, I can do that, too, but I prefer to wait for #5137 right now.

**Comment by captainsafia** [comment]
> If you want me to make a quick fix, I can do that, too, but I prefer to wait for #5137 right now.

We can wait for that PR. We've got a few more weeks before the June release anyways and we might need to shake out more fixes for other things.
