### ISSUE TITLE
RFC: Multiselect Cells

### ISSUE THREAD

**Issue by emeeks** [nteract/archived-desktop-app#5164]
**Is your feature request related to a problem? Please describe.**
There are actions we want to perform on a discrete group of cells rather than the whole notebook.

**Describe the solution you'd like**
I'd like to add a *multiselectCell* action that, when fired, adds (if it does not exist) or removes (if it does exist) the id of a cell to an array. This would be entirely separate from focusCell so that you might have a focusCell that is not even in the array of multiselected cells (not because I think that's useful but just acknowledging the possibility depending on how it's implemented downstream).

**Describe alternatives you've considered**
I thought about just adding an `is-multiselected` tag to a cell since that's trivial but it adds UI cruft to the saved notebook that doesn't make sense (when I open any other app where I multiselected, I do not expect my multiselection to still be there).

**Additional context**
From a selfish perspective this will help me better understand nteract actions and store for later work.

**Comment by captainsafia** [comment]
@emeeks Totally agree that using metadata to track this would be a little superfluous since multi-select state is not something that exists beyond the lifetime of the app.

I think it would be interesting to use the myths model to create a `mythic-multiselect` package that encapsulates this logic.

We'd start by defining a myth that outlines the type interface of the state.

```js
export const multiselect = createMythicPackage("multiselect")<
  {
    selectedCells: CellId[];
  }
>({
  initialState: {
    selectedCells: [],
  },
});
```

Then we define the actions that can be invoked to modify the list of selected cells.

```js
export const selectCell =
  multiselect.createMyth("selectCell")<number>({
    reduce: (state, action) =>
      state.updateIn(["selectedCells"], list => list.push(action.payload.id))
  });
export const unselectCell =
  multiselect.createMyth("unselectCell")<number>({
    reduce: (state, action) =>
      state.updateIn(["selectedCells"], list => list.remove(action.payload.id))
  });
```

Then we can invoke these actions from the UI.

Let me know if you have any follow-up questions.
