### ISSUE TITLE
Kernel doesn't stop running cells on Runtime error

### ISSUE THREAD

**Issue by kjcho-msft** [nteract/archived-desktop-app#5174]
**Application or Package Used**
 nteract desktop

**Describe the bug**
Kernel doesn't stop running cells on Runtime error

**To Reproduce**

1. Add two cells below
cell 1: raise RuntimeError("my error message")
cell 2: 1+1

2. Run all cells

**Expected behavior**
Kernel should stop running cells on Runtime error so the second cell should not be executed.

**Observed**
Both cells were executed.

**Screenshots**
![image](https://user-images.githubusercontent.com/26585299/85433325-219e3080-b539-11ea-8f19-9479991a6983.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: N/A. nteract desktop is used.
- Version: 0.23.1

**Comment by captainsafia** [comment]
So, continuing to execute even if there is a runtime exception in one of the cells has been standard in nteract for a while.

I cannot recall if this was an intentional decision or one of those things were we shipped a different experience, no one raised any alarms, and so we stuck at it.

I'm pretty flexible on whether we change this model or not. I do have a slight reservation because we recently changed the default behavior for output height (collapsed by default) and quite a few users weren't happy.

@MSeal @emeeks @willingc Thoughts?

**Comment by MSeal** [comment]
I know VSCode and nteract both have this behavior, but I don't think it should be the default Run All experience. `papermill` for example halts on exception unless the allow-error flag as does most (all?) the other notebook interfaces when running the whole notebook. I had chatted with the VSCode folks about it and I think they similarly had just had that as an early default, but it can lead to bad side-effects and confusing errors if you have cells below a failing cell that then try to execute. If you think of the notebook as either a script or a function extension you'd expect it to halt execution upon error rather than continuing computation in those contexts.

A real example where this has come up for me, is with a notebook which prepared and sent an email. If the email body generating cell fails, then a later cell that forms the email would send an email with no body because you hit run-all. That can be a quite problematic experience.

**Comment by willingc** [comment]
Hmm... if using `papermill` or `run all cells` then I agree with @MSeal about halt unless specific allow error. 

If running the notebook interactively by hand, I think that it's the user's choice to continue to run cells even if a prior cell had an error. I feel pretty strongly in this case that the kernel shouldn't prevent me from executing the next cell when I may be trying different approaches interactively.

**Comment by emeeks** [comment]
I agree with Carol as it reflects my own experience (I know the cell errored because of something else that's sloppy but I still want to shift-enter through the rest of it) but I think that run-all or any "expect it to run the cells while I'm not looking" should stop and fail on an error cell.

**Comment by captainsafia** [comment]
Alright! We can ship this as part of the July release. I'm more comfortable with that since the June release contained the new UI and I didn't want to introduce yet-another-thing in that release.

From an implementation perspective, we'll need to short-circuit the execution lifecycle when an `error()` type is emitted from the kernel. We'll probably need to refactor the epics a little bit so that:

* messages always go through the execution queue instead of emitting an `EXECUTE_CELL` action right away
* when an error is emitted from the kernel, clear the execution queue
* update the execute cell epic to read executions from the queue in the state instead of the action

**Comment by MSeal** [comment]
If I recall correctly the classic jupyter UI -> notebook server actually sends all of the execute cells to the kernel and when an error occurs you get an `abort` message back from the kernel for the future request(s). Which is also a viable path for implementation with a try catch pattern. It also is a little more resilient to closing your browser tab because the requests are pending on the kernel side, though I would still go with the approach that makes the code simplest as it's not much of an improvement anyway.

**Comment by captainsafia** [comment]
The two are complimentary. We still need a way to implement the "stop processing" event when the abort message is emitted from the kernel.

Tagging for July release.
