### ISSUE TITLE
I can't find the source code for @nteract/transforms

### ISSUE THREAD

**Issue by eric-wieser** [nteract/archived-desktop-app#5189]
I'm following the breadcrumbs for a possible nteract issue (https://github.com/pygae/pyganja/issues/46), but they run out at

https://github.com/microsoft/vscode-python/blob/6abd30e50a36283b97f25418c357738021d2e9c8/src/datascience-ui/interactive-common/transforms.tsx#L92-L95

I can find the [`@nteract/transforms` package on npm](https://www.npmjs.com/package/@nteract/transforms), but I haven't been able to find any evidence of the `JavaScriptTransform` class existing in this repo.

Could someone point me to where the source for `@nteract/transforms` is?

**Comment by eric-wieser** [comment]
I found an old copy at https://github.com/nteract/nteract/blob/v0.12.3/packages/transforms/src/javascript.js#L27, but that file is gone in master.

**Comment by captainsafia** [comment]
The nteract/transforms package was renamed to nteract/outputs a little over a year ago. Its sources are currently at https://github.com/nteract/outputs. Here's the code for the JavaScript transform: https://github.com/nteract/outputs/blob/master/packages/outputs/src/components/media/javascript.tsx.

Edit: Since the nteract/transforms package is over a year old and no longer maintained, the sources in nteract/outputs will be slightly different from what is published.
