### ISSUE TITLE
Export PDF doesn't work

### ISSUE THREAD

**Issue by codepatel** [nteract/archived-desktop-app#5277]
I tried this on a Mac OS Catalina as well as a Win10 PC. In both platforms, the Export PDF doesn't seem to work. See attached image below.

<img width="967" alt="image" src="https://user-images.githubusercontent.com/7637981/91647478-bed98180-ea20-11ea-9294-1b166a51708a.png">

**Comment by willingc** [comment]
Hi @codepatel, Thanks for the issue report. Today we released [v0.25](https://github.com/nteract/nteract/releases/tag/v0.25.0). Please give it a try and let us know if you still see the behavior. Thanks.

**Comment by codepatel** [comment]
I tried v0.25 on a Windows, and the Export->PDF still didn't work for me.

I didn't try v0.25 on Mac due to #5283

**Comment by codepatel** [comment]
@willingc , Also a report "request" feature might be add a Table of Contents in PDF, based on MD cells/heading and easy to navigate bookmarks in the PDF based on the MD cells. Please add this as a separate feature request if you think so.

**Comment by jarmokivekas** [comment]
+1 on this for v0.25.0 desktop app. I'm running on Ubuntu.

1. open any notebook
2. File -> Export -> PDF
3. The pdf is not created, and there is also no pdf export notification in the interface (you used to be able to open the pdf from the notification).

There are error messages in the developer tools console or stderr.


Another aside related to this, is using the PDF export menu toggles the cell `Extended Output` in the main UI, but not the cell toolbar menu.  I'm able to reliably reproduce this in one notebook, but not in all notebooks. Unfortunately I can't share the notebook due to its contents.

Note that the extended output is enabled in the menu, but the cell is not extended. Using Export > PDF again at this point extends the cell output, and the menu switch stays indicating the extended state:


![image](https://user-images.githubusercontent.com/3074453/92514238-3e820000-f21a-11ea-8fe5-b1552fb07ebd.png)

**Comment by captainsafia** [comment]
I'm gonna see if I can take a stab at finishing the PR that @jarmokivekas started for the October release.

**Comment by sammdu** [comment]
I don't know if this is helpful, but here are a couple other projects that attempted to implement PDF generation with Node.js/Electron:

https://github.com/marcbachmann/node-html-pdf
https://github.com/fraserxu/electron-pdf

I imagine even if we choose not to use them directly, they can still serve as reference.

**Comment by captainsafia** [comment]
Thanks -- this is actually fixed and will ship in the November release.
