### ISSUE TITLE
Light-colored icon for system tray

### ISSUE THREAD

**Issue by epassaro** [nteract/archived-desktop-app#5352]
**Is your feature request related to a problem? Please describe.**
`nteract` system tray icon is black and is not visible with dark styled desktop themes.

**Describe the solution you'd like**
A light-colored icon for system tray.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by captainsafia** [comment]
Thanks for opening this issue, @epassaro! [This StackOverflow response](https://stackoverflow.com/a/41998326) outlines the changes that we need to make to fix this.

**Comment by CrystallineCat** [comment]
I've noticed this issue on Ubuntu.

AFAICT, we're already set up for the method mentioned in the article @captainsafia linked, however, that method only seems to work on MacOS. I think we need to do something like this for other platforms: https://stackoverflow.com/questions/60333505/provide-different-dock-and-tray-icons-for-electron-based-app-on-mac

I've partially done this (not updating when the OS theme is changed) in #5353, since I was already touching the surrounding code:
```typescript
  const logo = (
    nativeTheme.shouldUseDarkColors ||
    process.platform === "darwin" // Macs support logo templates and selecting the right color automatically
  ) ? "logoTemplate" : "logoWhite";
```
It seems to work on Ubuntu, but I can't verify other platforms.

**Comment by captainsafia** [comment]
@CrystallineCat Thanks for taking a look at that!
