### ISSUE TITLE
IQSharp kernel

### ISSUE THREAD

**Issue by VarLad** [nteract/archived-desktop-app#5359]
nteract 0.26.0
Fedora 33 x86_64

The IQSharp kernel, which I got by running into my teminal

> dotnet tool install -g Microsoft.Quantum.IQSharp
> dotnet iqsharp install --user

from https://docs.microsoft.com/en-us/quantum/quickstarts/install-jupyter?tabs=tabid-dotnetcli

Works nicely on Jupyter
![Screenshot from 2020-11-16 17-26-43](https://user-images.githubusercontent.com/51269425/99249968-f510eb00-2830-11eb-8914-53302ae1bbf2.png)
And although nteract detects it, the kernel doesn't start.
![Screenshot from 2020-11-16 17-57-05](https://user-images.githubusercontent.com/51269425/99252727-6a7eba80-2835-11eb-92d7-89baee03fbd9.png)

The remaining kernels including the IJava kernel work in nteract. https://github.com/SpencerPark/IJava
![Screenshot from 2020-11-16 18-11-02](https://user-images.githubusercontent.com/51269425/99253694-31dfe080-2837-11eb-9176-6f7667a72c55.png)

They're installed in the /home/user/.local/share/jupyter/kernels/

**Comment by VarLad** [comment]
Also, when I set it as default, it does open
Although its forever stuck at the "launching" part!
![Screenshot from 2020-11-16 18-13-48](https://user-images.githubusercontent.com/51269425/99253950-9b5fef00-2837-11eb-93ad-fbc98460e709.png)

**Comment by willingc** [comment]
Hmm...I  did some troubleshooting this morning and can confirm it does not easily install on Mac Big Sur. It may be a dotnet / Big Sur thing. Will try another system later.

**Comment by captainsafia** [comment]
@cgranade I think we were taking a look at this a while back. Did we ever end up figuring out what is going on here?

**Comment by cgranade** [comment]
@captainsafia: I don't think so, no... got it narrowed down to how [the Microsoft.Jupyter.Core library](https://github.com/microsoft/jupyter-core/) used by IQ# handles startup and the first few Jupyter protocol messages, but I don't know that we found the exact issue. @rmshaffer may know more, as he's now code owner for IQ#. Would love to figure it out, as it'd be great to be able to use IQ# from nteract!

**Comment by VarLad** [comment]
Well, any update on this?

**Comment by rmshaffer** [comment]
After some debugging, this appears to be because the Microsoft.Jupyter.Core implementation (used by the IQ# kernel) does not send a `status` message with `execution_state: 'idle'` after sending the `kernel_info_reply` message. This seemingly causes nteract to continue to send `kernel_info_request` messages and never mark the kernel as ready. If I force that `status` message to be sent immediately after `kernel_info_reply`, things seem happy.

It might be possible to workaround this in nteract, but I believe this is a bug in Microsoft.Jupyter.Core. Per the [Jupyter messaging protocol documentation](https://jupyter-client.readthedocs.io/en/stable/messaging.html#kernel-status):
> Busy and idle messages should be sent before/after handling every request, not just execution.

I've opened https://github.com/microsoft/jupyter-core/issues/66 and will work on getting a fix in for this.

**Comment by captainsafia** [comment]
@rmshaffer Awesome! Thanks for looking into it. Closing this in favor of the other issue.
