### ISSUE TITLE
Evaluate electron spellcheck

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#550]
See https://github.com/paulcbetts/electron-spellchecker

**Comment by rgbkrk** [comment]
https://twitter.com/paulcbetts/status/755530992379568128

**Comment by captainsafia** [comment]
Closing this at the moment.

`electron-spellcheck` relies on the Chromium browser's spell checker. Browser spell checkers do not work on CodeMirror elements since they are not recognized as editable by the browser.

Our implementation for spellcheck will either have to rely on an alternate editor for CodeCells or implement spellcheck via something like typo.js.
