### ISSUE TITLE
Unable to run the nteract electron app following the steps in contribution.md

### ISSUE THREAD

**Issue by brism17** [nteract/archived-desktop-app#5644]
**Application or Package Used**
nteract desktop 
**Describe the bug**
Here is the error on wsl 
![image](https://user-images.githubusercontent.com/58003438/154380031-82183d3f-c498-4e1a-b70f-5998e1fc8964.png)
On windows the above error occurs with this additional output complaing about zeromq:
![image](https://user-images.githubusercontent.com/58003438/154544877-f704e6d5-90b5-4e85-a981-fcf072141f95.png)

This is the result I get when running yarn spawn in a separate window after running yarn build:desktop:watch.
This request : https://github.com/zeromq/zeromq.js/releases/download/v5.2.0/zeromq-v5.2.0-electron-v85-linux-x64.tar.gz Is returning 404s which seems to be the source of the error. I tried removing the ijavascript dependency which relies on the zeromq package and the launch still failed in the same way. 

**To Reproduce**
1. Clone the repo
2. Run yarn in a command prompt window. 
3. Run yarn  build: all
4. Run yarn build:desktop:watch
5. In a separate command prompt window run yarn spawn

(This happens both when trying to launch from windows command prompt and wsl)

**Expected behavior**
The spawn command to succeed and the electron app to be launched. 

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows
- Edition: Windows 11 Enterprise
- Os build: 22000.493
- Node Version : 16.13.2

**Comment by captainsafia** [comment]
By default, the Electron build will try to download one of the prebuilds for zeromq that are already provided. If there is no prebuild for the particular architecture and operating system combination that exists, the build will generate the zeromq build instead of using the prebuilds.

It does this using [node-gyp](https://github.com/nodejs/node-gyp) which is a native build tool for NodeJS.

It seems like for the WSL scenario, node-gyp failed due to an issue evaluating `openssl_ffi`. I found [this issue](https://github.com/nodejs/node-gyp/issues/2543) in the node-gyp repo which has some helpful pointers.

Maybe as a stab try downgrading the particular version of NodeJS used in the repo? There might be something funky with the build dependencies on Windows....

**Comment by brism17** [comment]
Thank you safia! I found the issue, I needed to downgrade my version of node to version 16.13.2 and install electron's dependencies with the following command `sudo apt install libnss3-dev libgdk-pixbuf2.0-dev libgtk-3-dev libxss-dev`
