### ISSUE TITLE
Plotly plotting not working

### ISSUE THREAD

**Issue by captainsafia** [nteract/archived-desktop-app#596]
@jackparmer discovered some funky issues when using Plotly's Python library in nteract in the latest alpha release.

![pasted image at 2016_08_15 09_04 pm](https://cloud.githubusercontent.com/assets/1857993/17687814/d1003992-6335-11e6-9710-ff76d4b03dae.png)

**Comment by rgbkrk** [comment]
It's expecting `define` to be set because it's relying on the (jupyter) notebook to be using requirejs. /cc @jdfreder

**Comment by jdfreder** [comment]
It'd probably make sense to find/make a shim for dynamically loaded AMD modules, because this wont be the only Jupyter notebook thing people will try to load- and it would be nice if we could fail gracefully.

As far as plotly is concerned, IIRC it's just defining an anonymous module, which the to-be shim should handle fine.

**Comment by rgbkrk** [comment]
Closing this one since we have native support for it and other data types directly.
