### ISSUE TITLE
Copying text in a codemirror area breaks entire app

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#613]
<img width="785" alt="screen shot 2016-08-20 at 7 57 05 am" src="https://cloud.githubusercontent.com/assets/836375/17831939/cd1aa3f2-66ab-11e6-87aa-e5c8b64aae0e.png">

Steps to reproduce:
- Type some code
- Select it, copy it
- Can't execute cells anymore

/cc @captainsafia does #592 fix this?

**Comment by captainsafia** [comment]
Yes. #592 should fix this. This happens because we currently have the keyboard handling for copy paste at the cell level.

I have some tests to push to #592 and then it can be merged. It'll drop coverage because I can't figure out how to test for the execution of instance functions on the Notebook component.

**Comment by rgbkrk** [comment]
It's ok if coverage drops. I promise to help with those tests since I'm cleaning up execution right now.

**Comment by jdfreder** [comment]
🐛

**Comment by rgbkrk** [comment]
This is now fixed, yet now I can't copy cells (was only trying for fun).
