### ISSUE TITLE
Setup a default kernel based on user

### ISSUE THREAD

**Issue by rgbkrk** [nteract/archived-desktop-app#620]
/cc @glyph who has a bunch of custom kernels and not the magical Python3 default kernel we expect.

**Comment by glyph** [comment]
My custom kernels are mostly just different virtualenvs for different projects, with different things installed into them.

**Comment by rgbkrk** [comment]
Very legitimate.

On a first usage, would you say it's fair to pick the first kernel we see and from there on users can pick a default kernel?

**Comment by glyph** [comment]
@rgbkrk That would be totally fine with me. Although it would be nice to have a defined "first" - lexicographical order maybe? :)

**Comment by rgbkrk** [comment]
This was "done" in #763 as a useful side effect of our app startup. Still want to think on configuring the default kernel as well as the order (we're currently at the mercy of `Object.keys`, which means we're at the mercy of property order).

**Comment by rgbkrk** [comment]
@captainsafia - here's a good one to add to the new config setup - default kernel (by name)

**Comment by AlJohri** [comment]
@rgbkrk one really nice feature of the jupyter web interface is that using the CLI, if I run: `jupyter notebook analysis.ipynb` within a virtualenv, it will automatically use the virtualenv's kernel without having to run `python -m ipykernel install`. I find that running `ipykernel install` can quickly end up with a ton of kernels in nteract's drop down menu since I use a virtualenv for each project (related #1041, https://github.com/nteract/nteract/issues/1576#issuecomment-331669619)

is there any way that running `nteract analysis.ipynb` within a virtualenv could automatically detect that its being run from within a virtualenv and start with the virtualenv's kernel if it exists? I know that running `jupyter-kernelspec list` within the virtualenv is able to find it:

```
$ pipenv run jupyter-kernelspec list
Available kernels:
  python3    /Users/johria/.local/share/virtualenvs/hss-gPwjJtJU/share/jupyter/kernels/python3
```

I do understand that this is a little more of an advanced user edgecase but, it would be great to sort of implicitly support this kind of usage when triggered from the CLI but don't surface it in the GUI in anyway. so in the end, I can run something like:

```
envdir envs/local pipenv run nteract analysis.ipynb
```

[`envdir`](https://envdir.readthedocs.io/en/latest/) creates a subshell with the environment variables defined in `envs/local` and [`pipenv`](https://pipenv.readthedocs.io/en/latest/) creates a subshell using the virtualenv. thus `nteract` would start from a shell with an active virtualenv and should ideally be able to find the kernel accordingly

does that sort of make sense? I already use `envdir envs/local pipenv run jupyter notebook analysis.ipynb` pretty regularly and it works great

**Comment by captainsafia** [comment]
Re-opening this.

There is currently an open PR for this feature at https://github.com/nteract/nteract/pull/4654.
