### ISSUE TITLE
`$ npm install` => `Failed at the zmq@2.14.0 install script 'node-gyp rebuild'.`

### ISSUE THREAD

**Issue by ghost** [nteract/archived-desktop-app#73]
So I properly logged in as suggested in #67 
then:

```
$ rm -rf ./composition
$ git clone git@github.com:nteract/composition.git
$ cd composition
$ npm install
```

And... surprise surprise:

![screen shot 2016-01-30 at 21 36 54](https://cloud.githubusercontent.com/assets/10885649/12698399/bb6a7830-c79b-11e5-9e0d-a0a20ff97ef3.png)

[npm-debug.log.zip](https://github.com/nteract/composition/files/110994/npm-debug.log.zip)

**Comment by rgbkrk** [comment]
Exciting! This is because we introduced our core binary dependency in #69 (which happened after the first install issue of the day :wink:)

Here are some instructions we should port over: https://github.com/nteract/enchannel-zmq-backend#zeromq-dependency

If you're using homebrew on your Mac, `brew install pkg-config zeromq`. You may run into other node-gyp fun times.

Long term solution: prebuilt versions of zmq for everyone: #1

**Comment by rgbkrk** [comment]
This should be going ok now and upstream work is ongoing for zmq and node (as well as the zmq-prebuilt library that @minrk has been working on). Feel free to re-open if you run into more troubles.
