### ISSUE TITLE
Restarting kernel does not preserve working directory

### ISSUE THREAD

**Issue by darthoctopus** [nteract/archived-desktop-app#919]
when the kernel is restarted with a previously saved notebook, the working directory is reset to the user's home directory, rather than the path of the open ipython notebook.

**Comment by jdetle** [comment]
Thanks for the issue! By any chance could to provide some code to reproduce the error? I can't seem to recreate the issue on my computer. 
Some questions: 
What OS are you using? 
What version of nteract are you running?

**Comment by rgbkrk** [comment]
Reproduction steps:

Launch the example intro notebook

```
 npm run start example-notebooks/intro.ipynb
```

Run

```
!pwd
```

example-notebooks is the directory

Restart the kernel (by menu) and run

```
!pwd
```

home directory is the result

**Comment by captainsafia** [comment]
I think this is due to the way that we are passing data from our action creators to our epics.

The `newKernel` action invoked in the menu sends a dispatch to the `LAUNCH_KERNEL` action which expects the action to be structured like this `{kernelSpecName: 'python3', cwd: '/usr/blah/blah'}` what we are actually doing now is passing it `{kernelSpecName: 'python3', cwd: {cwd: '/usr/blah/blah'}`. I believe this triggers the fallback code that has fresh kernels unassociated with a notebook launch at ~ to start.
