### ISSUE TITLE
Linkify URLs in plain text output

### ISSUE THREAD

**Issue by gnestor** [nteract/archived-desktop-app#993]
notebook supports this (but I noticed that jupyterlab doesn't yet).

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/512354/19318998/ad0df8a6-905f-11e6-98fc-9bad00e71403.png)

**Comment by gnestor** [comment]
@rgbkrk Does it make sense to add this feature to [ansi-to-react](https://github.com/nteract/ansi-to-react)?

**Comment by rgbkrk** [comment]
I'm not sure where this would belong. I'd rather we finish off handling line feeds and other ANSI/terminal codes before we add automatic linkification.

**Comment by gnestor** [comment]
I was looking at the anser library used in ansi-to-react and there is a linkify method which would require we use its `ansiToHtml` method vs. `ansiToJson` and then `dangerouslySetInnerHTML`.

**Comment by rgbkrk** [comment]
While convenient to use the linkify, it comes at the cost of reducing what can be displayed in untrusted notebooks. All outputs from streams would not be shown on opening the notebook.

**Comment by gnestor** [comment]
True. What if we just rolled our own?

``` js
function inlineBundleToReact(bundle, key) {
  // Very rough, use a URL regex and assuming that `anser.ansiToJson` parses URLs into separate items
  if (bundle.content.includes('http') return React.createElement('a', {
    href: bundle.content,
    style: bundle.style,
    key,
  }, bundle.content);
  return React.createElement('span', {
    style: bundle.style,
    key,
  }, bundle.content);
}
```

Would we be able to display this in untrusted notebooks?

**Comment by rgbkrk** [comment]
Yeah, an approach that keeps content as `textContent`, can be displayed. When strings are the `children` of a React Element, they are done as `textContent` which is what you've done above.

There's going to be some amount of tripping on escape codes here. An admittedly naive approach that would keep the console consistent would be to do a second pass on the bundles returned by `ansiToJson`.

As for rolling our own, I recall ~Hyperterm~ Hyper.app talking about trying to do terminal state in a way where they could push down state into a React component more effectively. At a high level, the current state of the terminal is an intermediate reduction on the stream of character. Stepping out of that abstract way to say it, I wish we had a function with a signature like this:

```
function ttyReducer(state: ttyState, text): ttyState
```

Where ttyState is (in all likelihood) a string. This is important to me because we'd be able to store the last state in the notebook document rather than the entire stream of text from stdout.

**Comment by gnestor** [comment]
So how about we modify [inlineBundleToReact](inlineBundleToReact) so that it returns an <a> if the content is a URL and a <span> if not?

**Comment by rgbkrk** [comment]
Somehow I missed this - yes, I think we should be able to go from source text on stream output (or text/plain) and include linked URLs.

**Comment by gnestor** [comment]
Ok, should it live in `inlineBundleToReact`? And should it just parse words and render them as an `<a>` if they match an URL regex pattern?

**Comment by rgbkrk** [comment]
Yeah that sounds like a good option. If it makes it easier to work with, feel free to bring it into nteract/nteract as yet-another-package-for-export.
